export default {
  index: 'Overview',

  '-- DOM & UI': {
    type: 'separator',
    title: 'DOM & UI'
  },
  useClickOutside: 'useClickOutside',
  useSystemColorScheme: 'useSystemColorScheme',
  useElementSize: 'useElementSize',
  useEventListener: 'useEventListener',
  useFocusReturn: 'useFocusReturn',
  useFocusTrap: 'useFocusTrap',
  useFocusWithin: 'useFocusWithin',
  useFullscreen: 'useFullscreen',
  useHotkeys: 'useHotkeys',
  useHover: 'useHover',
  useInViewport: 'useInViewport',
  useIntersection: 'useIntersection',
  useMediaQuery: 'useMediaQuery',
  useMouse: 'useMouse',
  useMove: 'useMove',
  useMutationObserver: 'useMutationObserver',
  useOrientation: 'useOrientation',
  useReducedMotion: 'useReducedMotion',
  useResizeObserver: 'useResizeObserver',
  useScrollIntoView: 'useScrollIntoView',
  useScrollSpy: 'useScrollSpy',
  useViewportSize: 'useViewportSize',
  useWindowEvent: 'useWindowEvent',
  useWindowScroll: 'useWindowScroll',

  '-- State Management': {
    type: 'separator',
    title: 'State Management'
  },
  useCounter: 'useCounter',
  useDebouncedCallback: 'useDebouncedCallback',
  useDebouncedState: 'useDebouncedState',
  useDebouncedValue: 'useDebouncedValue',
  useDisclosure: 'useDisclosure',
  useId: 'useId',
  useInputState: 'useInputState',
  useListState: 'useListState',
  useLocalStorage: 'useLocalStorage',
  useMap: 'useMap',
  usePagination: 'usePagination',
  usePrevious: 'usePrevious',
  useQueue: 'useQueue',
  useSet: 'useSet',
  useSetState: 'useSetState',
  useStateHistory: 'useStateHistory',
  useThrottledCallback: 'useThrottledCallback',
  useThrottledState: 'useThrottledState',
  useThrottledValue: 'useThrottledValue',
  useToggle: 'useToggle',
  useUncontrolled: 'useUncontrolled',
  useValidatedState: 'useValidatedState',

  '-- Utilities': {
    type: 'separator',
    title: 'Utilities'
  },
  useClipboard: 'useClipboard',
  useDocumentTitle: 'useDocumentTitle',
  useDocumentVisibility: 'useDocumentVisibility',
  useEyeDropper: 'useEyeDropper',
  useFavicon: 'useFavicon',
  useFetch: 'useFetch',
  useFileDialog: 'useFileDialog',
  useHash: 'useHash',
  useHeadroom: 'useHeadroom',
  useIdle: 'useIdle',
  useInterval: 'useInterval',
  useMergedRef: 'useMergedRef',
  useNetwork: 'useNetwork',
  useOs: 'useOs',
  usePageLeave: 'usePageLeave',
  useTextSelection: 'useTextSelection',
  useTimeout: 'useTimeout',
  useURLQueryState: 'useURLQueryState',

  '-- Lifecycle': {
    type: 'separator',
    title: 'Lifecycle'
  },
  useDidUpdate: 'useDidUpdate',
  useForceUpdate: 'useForceUpdate',
  useIsFirstRender: 'useIsFirstRender',
  useIsomorphicEffect: 'useIsomorphicEffect',
  useLogger: 'useLogger',
  useMounted: 'useMounted',
  useShallowEffect: 'useShallowEffect'
}
