/**
 * DO NOT EDIT THIS FILE, THE CONTENT IS AUTO-GENERATED
 * RUN `pnpm run build:icon` TO RE-GENERATE
 */
import AiExplore01 from './react/AiExplore01'
import AlertCircle from './react/AlertCircle'
import AlertTriangle from './react/AlertTriangle'
import AlertTriangleFill from './react/AlertTriangleFill'
import AlignLeft01 from './react/AlignLeft01'
import AlignRight01 from './react/AlignRight01'
import ArrowDown from './react/ArrowDown'
import ArrowLeft from './react/ArrowLeft'
import ArrowRight from './react/ArrowRight'
import ArrowUp from './react/ArrowUp'
import Atom01 from './react/Atom01'
import BarChart04 from './react/BarChart04'
import BarChart07 from './react/BarChart07'
import BarChart08 from './react/BarChart08'
import BarHorizontal from './react/BarHorizontal'
import BarVertical from './react/BarVertical'
import BookClosed from './react/BookClosed'
import BookOpen02 from './react/BookOpen02'
import Brackets from './react/Brackets'
import BracketsEllipses from './react/BracketsEllipses'
import Breakdown02 from './react/Breakdown02'
import Building05 from './react/Building05'
import Calendar from './react/Calendar'
import ChatRobot from './react/ChatRobot'
import Check from './react/Check'
import CheckCircle from './react/CheckCircle'
import CheckCirclebroken from './react/CheckCirclebroken'
import CheckSquareBroken from './react/CheckSquareBroken'
import CheckVerified02 from './react/CheckVerified02'
import ChevronDown from './react/ChevronDown'
import ChevronDownFill from './react/ChevronDownFill'
import ChevronLeft from './react/ChevronLeft'
import ChevronRight from './react/ChevronRight'
import ChevronRightFill from './react/ChevronRightFill'
import ChevronUp from './react/ChevronUp'
import ChevronVerticalExpand from './react/ChevronVerticalExpand'
import ChevronVerticalShrink from './react/ChevronVerticalShrink'
import Clock from './react/Clock'
import CodeBrowser from './react/CodeBrowser'
import CodeCircle02 from './react/CodeCircle02'
import CodeCircle03 from './react/CodeCircle03'
import Collapse08 from './react/Collapse08'
import Connect from './react/Connect'
import Copy01 from './react/Copy01'
import Copy03 from './react/Copy03'
import Copy07 from './react/Copy07'
import CurrencyDollarCircle from './react/CurrencyDollarCircle'
import CursorClick01 from './react/CursorClick01'
import DataApiSystem from './react/DataApiSystem'
import Database from './react/Database'
import Database01 from './react/Database01'
import Database03 from './react/Database03'
import DatabseTable from './react/DatabseTable'
import Dataflow03 from './react/Dataflow03'
import DataService from './react/DataService'
import DataServiceAdd from './react/DataServiceAdd'
import DotPoints01 from './react/DotPoints01'
import DotsHorizontal from './react/DotsHorizontal'
import DotsVertical from './react/DotsVertical'
import Download01 from './react/Download01'
import DownloadCloud01 from './react/DownloadCloud01'
import DragIn from './react/DragIn'
import Edit03 from './react/Edit03'
import Edit05 from './react/Edit05'
import Eraser from './react/Eraser'
import Expand01 from './react/Expand01'
import Expand08 from './react/Expand08'
import Eye from './react/Eye'
import EyeOff from './react/EyeOff'
import FaceNeutral from './react/FaceNeutral'
import FaceSmile from './react/FaceSmile'
import File02 from './react/File02'
import File05 from './react/File05'
import File06 from './react/File06'
import FileImport02 from './react/FileImport02'
import FilterFunnel01 from './react/FilterFunnel01'
import FilterLines from './react/FilterLines'
import FolderSettings from './react/FolderSettings'
import Github from './react/Github'
import Glasses01 from './react/Glasses01'
import Globe01 from './react/Globe01'
import Grid01 from './react/Grid01'
import HandsDown from './react/HandsDown'
import HandsDownFill from './react/HandsDownFill'
import HandsUp from './react/HandsUp'
import HandsUpFill from './react/HandsUpFill'
import HeartHand from './react/HeartHand'
import HelpCircle from './react/HelpCircle'
import HomeLine from './react/HomeLine'
import Inbox01 from './react/Inbox01'
import Info2 from './react/Info2'
import InfoCircle from './react/InfoCircle'
import InfoHexagon from './react/InfoHexagon'
import Key02 from './react/Key02'
import LaygroundGrid02 from './react/LaygroundGrid02'
import LayoutAlt03 from './react/LayoutAlt03'
import LayoutBottom from './react/LayoutBottom'
import LayoutBottomFill from './react/LayoutBottomFill'
import LayoutLeft from './react/LayoutLeft'
import LayoutLeftFill from './react/LayoutLeftFill'
import LayoutRight from './react/LayoutRight'
import LayoutRightFill from './react/LayoutRightFill'
import LayoutTop from './react/LayoutTop'
import LayoutTopFill from './react/LayoutTopFill'
import LeftIndent01 from './react/LeftIndent01'
import LifeBuoy01 from './react/LifeBuoy01'
import LineChart from './react/LineChart'
import LineChartUp01 from './react/LineChartUp01'
import Link03 from './react/Link03'
import LinkExternal01 from './react/LinkExternal01'
import List from './react/List'
import Lock01 from './react/Lock01'
import LockUnlocked01 from './react/LockUnlocked01'
import LogOut03 from './react/LogOut03'
import MagicWand02 from './react/MagicWand02'
import MediaGithub from './react/MediaGithub'
import MediaGithubFill from './react/MediaGithubFill'
import MediaGoogle from './react/MediaGoogle'
import MediaMicrosoft from './react/MediaMicrosoft'
import Menu01 from './react/Menu01'
import MenuLeft from './react/MenuLeft'
import MenuRight from './react/MenuRight'
import MessageChatSquare from './react/MessageChatSquare'
import MessageSquare02 from './react/MessageSquare02'
import MessageTextSquare01 from './react/MessageTextSquare01'
import MessageTextSquare02 from './react/MessageTextSquare02'
import Minimize01 from './react/Minimize01'
import Minus from './react/Minus'
import MinusCircle from './react/MinusCircle'
import Moon01 from './react/Moon01'
import NotificationBox from './react/NotificationBox'
import Numberic from './react/Numberic'
import OpenAi from './react/OpenAi'
import OrientationHorizontalFill from './react/OrientationHorizontalFill'
import OrientationVerticalFill from './react/OrientationVerticalFill'
import PackagePlus from './react/PackagePlus'
import ParagraphSpacing from './react/ParagraphSpacing'
import PauseCircle from './react/PauseCircle'
import Pencil01 from './react/Pencil01'
import PieChart03 from './react/PieChart03'
import PlayCircle from './react/PlayCircle'
import Plus from './react/Plus'
import PlusSquare from './react/PlusSquare'
import Question from './react/Question'
import Redeploy from './react/Redeploy'
import RefreshCw01 from './react/RefreshCw01'
import RefreshCw02 from './react/RefreshCw02'
import RefreshCw04 from './react/RefreshCw04'
import Repeat04 from './react/Repeat04'
import Right from './react/Right'
import RightIndent01 from './react/RightIndent01'
import Rocket02 from './react/Rocket02'
import Run from './react/Run'
import RunFill from './react/RunFill'
import Scale02 from './react/Scale02'
import Scale03 from './react/Scale03'
import SearchLg from './react/SearchLg'
import SeeMore from './react/SeeMore'
import SeeShort from './react/SeeShort'
import Send03 from './react/Send03'
import Series from './react/Series'
import Server02 from './react/Server02'
import Server05 from './react/Server05'
import Service from './react/Service'
import Settings01 from './react/Settings01'
import Settings02 from './react/Settings02'
import Shield03 from './react/Shield03'
import ShieldTick from './react/ShieldTick'
import ShieldUser from './react/ShieldUser'
import Star04 from './react/Star04'
import String01 from './react/String01'
import Sun from './react/Sun'
import SwitchHorizontal02 from './react/SwitchHorizontal02'
import SwitchVertical02 from './react/SwitchVertical02'
import SystemDatabase from './react/SystemDatabase'
import SystemMode from './react/SystemMode'
import Table from './react/Table'
import Tools from './react/Tools'
import Trash01 from './react/Trash01'
import Types02 from './react/Types02'
import UploadCloud01 from './react/UploadCloud01'
import UserCircle from './react/UserCircle'
import Users01 from './react/Users01'
import UsersPlus from './react/UsersPlus'
import Variable from './react/Variable'
import Wifi from './react/Wifi'
import XAxis from './react/XAxis'
import XCircle from './react/XCircle'
import XClose from './react/XClose'
import YAxis from './react/YAxis'

export const ICON_MAP = {
  AiExplore01,
  AlertCircle,
  AlertTriangle,
  AlertTriangleFill,
  AlignLeft01,
  AlignRight01,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom01,
  BarChart04,
  BarChart07,
  BarChart08,
  BarHorizontal,
  BarVertical,
  BookClosed,
  BookOpen02,
  Brackets,
  BracketsEllipses,
  Breakdown02,
  Building05,
  Calendar,
  ChatRobot,
  Check,
  CheckCircle,
  CheckCirclebroken,
  CheckSquareBroken,
  CheckVerified02,
  ChevronDown,
  ChevronDownFill,
  ChevronLeft,
  ChevronRight,
  ChevronRightFill,
  ChevronUp,
  ChevronVerticalExpand,
  ChevronVerticalShrink,
  Clock,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Collapse08,
  Connect,
  Copy01,
  Copy03,
  Copy07,
  CurrencyDollarCircle,
  CursorClick01,
  DataApiSystem,
  DataService,
  DataServiceAdd,
  Database,
  Database01,
  Database03,
  DatabseTable,
  Dataflow03,
  DotPoints01,
  DotsHorizontal,
  DotsVertical,
  Download01,
  DownloadCloud01,
  DragIn,
  Edit03,
  Edit05,
  Eraser,
  Expand01,
  Expand08,
  Eye,
  EyeOff,
  FaceNeutral,
  FaceSmile,
  File02,
  File05,
  File06,
  FileImport02,
  FilterFunnel01,
  FilterLines,
  FolderSettings,
  Github,
  Glasses01,
  Grid01,
  Globe01,
  HandsDown,
  HandsDownFill,
  HandsUp,
  HandsUpFill,
  HeartHand,
  HelpCircle,
  HomeLine,
  Inbox01,
  Info2,
  InfoCircle,
  InfoHexagon,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LayoutBottom,
  LayoutBottomFill,
  LayoutLeft,
  LayoutLeftFill,
  LayoutRight,
  LayoutRightFill,
  LayoutTop,
  LayoutTopFill,
  LeftIndent01,
  LifeBuoy01,
  LineChart,
  LineChartUp01,
  Link03,
  LinkExternal01,
  List,
  Lock01,
  LockUnlocked01,
  LogOut03,
  MagicWand02,
  MediaGithub,
  MediaGithubFill,
  MediaGoogle,
  MediaMicrosoft,
  Menu01,
  MenuLeft,
  MenuRight,
  MessageChatSquare,
  MessageSquare02,
  MessageTextSquare01,
  MessageTextSquare02,
  Minimize01,
  Minus,
  MinusCircle,
  Moon01,
  NotificationBox,
  Numberic,
  OpenAi,
  OrientationHorizontalFill,
  OrientationVerticalFill,
  PackagePlus,
  ParagraphSpacing,
  PauseCircle,
  Pencil01,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  Question,
  Redeploy,
  RefreshCw01,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Rocket02,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  SeeMore,
  SeeShort,
  Send03,
  Series,
  Server02,
  Server05,
  Service,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  ShieldUser,
  Star04,
  String01,
  Sun,
  SwitchHorizontal02,
  SwitchVertical02,
  SystemDatabase,
  SystemMode,
  Table,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  UsersPlus,
  Variable,
  Wifi,
  XAxis,
  XCircle,
  XClose,
  YAxis
}

export {
  AiExplore01,
  AlertCircle,
  AlertTriangle,
  AlertTriangleFill,
  AlignLeft01,
  AlignRight01,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom01,
  BarChart04,
  BarChart07,
  BarChart08,
  BarHorizontal,
  BarVertical,
  BookClosed,
  BookOpen02,
  Brackets,
  BracketsEllipses,
  Breakdown02,
  Building05,
  Calendar,
  ChatRobot,
  Check,
  CheckCircle,
  CheckCirclebroken,
  CheckSquareBroken,
  CheckVerified02,
  ChevronDown,
  ChevronDownFill,
  ChevronLeft,
  ChevronRight,
  ChevronRightFill,
  ChevronUp,
  ChevronVerticalExpand,
  ChevronVerticalShrink,
  Clock,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Collapse08,
  Connect,
  Copy01,
  Copy03,
  Copy07,
  CurrencyDollarCircle,
  CursorClick01,
  DataApiSystem,
  DataService,
  DataServiceAdd,
  Database,
  Database01,
  Database03,
  DatabseTable,
  Dataflow03,
  DotPoints01,
  DotsHorizontal,
  DotsVertical,
  Download01,
  DownloadCloud01,
  DragIn,
  Edit03,
  Edit05,
  Eraser,
  Expand01,
  Expand08,
  Eye,
  EyeOff,
  FaceNeutral,
  FaceSmile,
  File02,
  File05,
  File06,
  FileImport02,
  FilterFunnel01,
  FilterLines,
  FolderSettings,
  Github,
  Glasses01,
  Grid01,
  Globe01,
  HandsDown,
  HandsDownFill,
  HandsUp,
  HandsUpFill,
  HeartHand,
  HelpCircle,
  HomeLine,
  Inbox01,
  Info2,
  InfoCircle,
  InfoHexagon,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LayoutBottom,
  LayoutBottomFill,
  LayoutLeft,
  LayoutLeftFill,
  LayoutRight,
  LayoutRightFill,
  LayoutTop,
  LayoutTopFill,
  LeftIndent01,
  LifeBuoy01,
  LineChart,
  LineChartUp01,
  Link03,
  LinkExternal01,
  List,
  Lock01,
  LockUnlocked01,
  LogOut03,
  MagicWand02,
  MediaGithub,
  MediaGithubFill,
  MediaGoogle,
  MediaMicrosoft,
  Menu01,
  MenuLeft,
  MenuRight,
  MessageChatSquare,
  MessageSquare02,
  MessageTextSquare01,
  MessageTextSquare02,
  Minimize01,
  Minus,
  MinusCircle,
  Moon01,
  NotificationBox,
  Numberic,
  OpenAi,
  OrientationHorizontalFill,
  OrientationVerticalFill,
  PackagePlus,
  ParagraphSpacing,
  PauseCircle,
  Pencil01,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  Question,
  Redeploy,
  RefreshCw01,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Rocket02,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  SeeMore,
  SeeShort,
  Send03,
  Series,
  Server02,
  Server05,
  Service,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  ShieldUser,
  Star04,
  String01,
  Sun,
  SwitchHorizontal02,
  SwitchVertical02,
  SystemDatabase,
  SystemMode,
  Table,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  UsersPlus,
  Variable,
  Wifi,
  XAxis,
  XCircle,
  XClose,
  YAxis
}
