/**
 * DO NOT EDIT THIS FILE, THE CONTENT IS AUTO-GENERATED
 * RUN `pnpm run build:icon` TO RE-GENERATE
 */
import Activity from './react/Activity'
import ActivityHeart from './react/ActivityHeart'
import AiExplore01 from './react/AiExplore01'
import AiMessage from './react/AiMessage'
import Airplay from './react/Airplay'
import Airpods from './react/Airpods'
import AlarmClock from './react/AlarmClock'
import AlarmClockCheck from './react/AlarmClockCheck'
import AlarmClockMinus from './react/AlarmClockMinus'
import AlarmClockOff from './react/AlarmClockOff'
import AlarmClockPlus from './react/AlarmClockPlus'
import AlertCircle from './react/AlertCircle'
import AlertHexagon from './react/AlertHexagon'
import AlertOctagon from './react/AlertOctagon'
import AlertSquare from './react/AlertSquare'
import AlertTriangle from './react/AlertTriangle'
import AlertTriangleFill from './react/AlertTriangleFill'
import AlignBottom01 from './react/AlignBottom01'
import AlignBottom02 from './react/AlignBottom02'
import AlignCenter from './react/AlignCenter'
import AlignHorizontalCentre01 from './react/AlignHorizontalCentre01'
import AlignHorizontalCentre02 from './react/AlignHorizontalCentre02'
import AlignJustify from './react/AlignJustify'
import AlignLeft from './react/AlignLeft'
import AlignLeft01 from './react/AlignLeft01'
import AlignLeft02 from './react/AlignLeft02'
import AlignRight from './react/AlignRight'
import AlignRight01 from './react/AlignRight01'
import AlignRight02 from './react/AlignRight02'
import AlignTopArrow01 from './react/AlignTopArrow01'
import AlignTopArrow02 from './react/AlignTopArrow02'
import AlignVerticalCenter01 from './react/AlignVerticalCenter01'
import AlignVerticalCenter02 from './react/AlignVerticalCenter02'
import Anchor from './react/Anchor'
import Annotation from './react/Annotation'
import AnnotationAlert from './react/AnnotationAlert'
import AnnotationCheck from './react/AnnotationCheck'
import AnnotationDots from './react/AnnotationDots'
import AnnotationHeart from './react/AnnotationHeart'
import AnnotationInfo from './react/AnnotationInfo'
import AnnotationPlus from './react/AnnotationPlus'
import AnnotationQuestion from './react/AnnotationQuestion'
import AnnotationX from './react/AnnotationX'
import Announcement01 from './react/Announcement01'
import Announcement02 from './react/Announcement02'
import Announcement03 from './react/Announcement03'
import Archive from './react/Archive'
import ArrowBlockDown from './react/ArrowBlockDown'
import ArrowBlockLeft from './react/ArrowBlockLeft'
import ArrowBlockRight from './react/ArrowBlockRight'
import ArrowBlockUp from './react/ArrowBlockUp'
import ArrowCircleBrokenDown from './react/ArrowCircleBrokenDown'
import ArrowCircleBrokenDownLeft from './react/ArrowCircleBrokenDownLeft'
import ArrowCircleBrokenDownRight from './react/ArrowCircleBrokenDownRight'
import ArrowCircleBrokenLeft from './react/ArrowCircleBrokenLeft'
import ArrowCircleBrokenRight from './react/ArrowCircleBrokenRight'
import ArrowCircleBrokenUp from './react/ArrowCircleBrokenUp'
import ArrowCircleBrokenUpLeft from './react/ArrowCircleBrokenUpLeft'
import ArrowCircleBrokenUpRight from './react/ArrowCircleBrokenUpRight'
import ArrowCircleDown from './react/ArrowCircleDown'
import ArrowCircleDownLeft from './react/ArrowCircleDownLeft'
import ArrowCircleDownRight from './react/ArrowCircleDownRight'
import ArrowCircleLeft from './react/ArrowCircleLeft'
import ArrowCircleRight from './react/ArrowCircleRight'
import ArrowCircleUp from './react/ArrowCircleUp'
import ArrowCircleUpLeft from './react/ArrowCircleUpLeft'
import ArrowCircleUpRight from './react/ArrowCircleUpRight'
import ArrowDown from './react/ArrowDown'
import ArrowDownLeft from './react/ArrowDownLeft'
import ArrowDownRight from './react/ArrowDownRight'
import ArrowLeft from './react/ArrowLeft'
import ArrowNarrowDown from './react/ArrowNarrowDown'
import ArrowNarrowDownLeft from './react/ArrowNarrowDownLeft'
import ArrowNarrowDownRight from './react/ArrowNarrowDownRight'
import ArrowNarrowLeft from './react/ArrowNarrowLeft'
import ArrowNarrowRight from './react/ArrowNarrowRight'
import ArrowNarrowUp from './react/ArrowNarrowUp'
import ArrowNarrowUpLeft from './react/ArrowNarrowUpLeft'
import ArrowNarrowUpRight from './react/ArrowNarrowUpRight'
import ArrowRight from './react/ArrowRight'
import ArrowsDown from './react/ArrowsDown'
import ArrowsLeft from './react/ArrowsLeft'
import ArrowSquareDown from './react/ArrowSquareDown'
import ArrowSquareDownLeft from './react/ArrowSquareDownLeft'
import ArrowSquareDownRight from './react/ArrowSquareDownRight'
import ArrowSquareLeft from './react/ArrowSquareLeft'
import ArrowSquareRight from './react/ArrowSquareRight'
import ArrowSquareUp from './react/ArrowSquareUp'
import ArrowSquareUpLeft from './react/ArrowSquareUpLeft'
import ArrowSquareUpRight from './react/ArrowSquareUpRight'
import ArrowsRight from './react/ArrowsRight'
import ArrowsTriangle from './react/ArrowsTriangle'
import ArrowsUp from './react/ArrowsUp'
import ArrowUp from './react/ArrowUp'
import ArrowUpLeft from './react/ArrowUpLeft'
import ArrowUpRight from './react/ArrowUpRight'
import Asterisk01 from './react/Asterisk01'
import Asterisk02 from './react/Asterisk02'
import Atom01 from './react/Atom01'
import Atom02 from './react/Atom02'
import AtSign from './react/AtSign'
import Attachment01 from './react/Attachment01'
import Attachment02 from './react/Attachment02'
import Award01 from './react/Award01'
import Award02 from './react/Award02'
import Award03 from './react/Award03'
import Award04 from './react/Award04'
import Award05 from './react/Award05'
import Backpack from './react/Backpack'
import Bank from './react/Bank'
import BankNote01 from './react/BankNote01'
import BankNote02 from './react/BankNote02'
import BankNote03 from './react/BankNote03'
import BarChart01 from './react/BarChart01'
import BarChart02 from './react/BarChart02'
import BarChart03 from './react/BarChart03'
import BarChart04 from './react/BarChart04'
import BarChart05 from './react/BarChart05'
import BarChart06 from './react/BarChart06'
import BarChart07 from './react/BarChart07'
import BarChart08 from './react/BarChart08'
import BarChart09 from './react/BarChart09'
import BarChart10 from './react/BarChart10'
import BarChart11 from './react/BarChart11'
import BarChart12 from './react/BarChart12'
import BarChartCircle01 from './react/BarChartCircle01'
import BarChartCircle02 from './react/BarChartCircle02'
import BarChartCircle03 from './react/BarChartCircle03'
import BarChartSquare01 from './react/BarChartSquare01'
import BarChartSquare02 from './react/BarChartSquare02'
import BarChartSquare03 from './react/BarChartSquare03'
import BarChartSquareDown from './react/BarChartSquareDown'
import BarChartSquareMinus from './react/BarChartSquareMinus'
import BarChartSquarePlus from './react/BarChartSquarePlus'
import BarChartSquareUp from './react/BarChartSquareUp'
import BarHorizontal from './react/BarHorizontal'
import BarLineChart from './react/BarLineChart'
import BarVertical from './react/BarVertical'
import BatteryCharging01 from './react/BatteryCharging01'
import BatteryCharging02 from './react/BatteryCharging02'
import BatteryEmpty from './react/BatteryEmpty'
import BatteryFull from './react/BatteryFull'
import BatteryLow from './react/BatteryLow'
import BatteryMid from './react/BatteryMid'
import Beaker01 from './react/Beaker01'
import Beaker02 from './react/Beaker02'
import Bell01 from './react/Bell01'
import Bell02 from './react/Bell02'
import Bell03 from './react/Bell03'
import Bell04 from './react/Bell04'
import BellMinus from './react/BellMinus'
import BellOff01 from './react/BellOff01'
import BellOff02 from './react/BellOff02'
import BellOff03 from './react/BellOff03'
import BellPlus from './react/BellPlus'
import BellRinging01 from './react/BellRinging01'
import BellRinging02 from './react/BellRinging02'
import BellRinging03 from './react/BellRinging03'
import BellRinging04 from './react/BellRinging04'
import BezierCurve01 from './react/BezierCurve01'
import BezierCurve02 from './react/BezierCurve02'
import BezierCurve03 from './react/BezierCurve03'
import BluetoothConnect from './react/BluetoothConnect'
import BluetoothOff from './react/BluetoothOff'
import BluetoothOn from './react/BluetoothOn'
import BluetoothSignal from './react/BluetoothSignal'
import Bold01 from './react/Bold01'
import Bold02 from './react/Bold02'
import BoldSquare from './react/BoldSquare'
import BookClosed from './react/BookClosed'
import Bookmark from './react/Bookmark'
import BookmarkAdd from './react/BookmarkAdd'
import BookmarkCheck from './react/BookmarkCheck'
import BookmarkMinus from './react/BookmarkMinus'
import BookmarkX from './react/BookmarkX'
import BookOpen01 from './react/BookOpen01'
import BookOpen02 from './react/BookOpen02'
import Box from './react/Box'
import Brackets from './react/Brackets'
import BracketsCheck from './react/BracketsCheck'
import BracketsEllipses from './react/BracketsEllipses'
import BracketsMinus from './react/BracketsMinus'
import BracketsPlus from './react/BracketsPlus'
import BracketsSlash from './react/BracketsSlash'
import BracketsX from './react/BracketsX'
import Breakdown02 from './react/Breakdown02'
import Briefcase01 from './react/Briefcase01'
import Briefcase02 from './react/Briefcase02'
import Browser from './react/Browser'
import Brush01 from './react/Brush01'
import Brush02 from './react/Brush02'
import Brush03 from './react/Brush03'
import Building01 from './react/Building01'
import Building02 from './react/Building02'
import Building03 from './react/Building03'
import Building04 from './react/Building04'
import Building05 from './react/Building05'
import Building06 from './react/Building06'
import Building07 from './react/Building07'
import Building08 from './react/Building08'
import Bus from './react/Bus'
import Calculator from './react/Calculator'
import Calendar from './react/Calendar'
import CalendarCheck01 from './react/CalendarCheck01'
import CalendarCheck02 from './react/CalendarCheck02'
import CalendarDate from './react/CalendarDate'
import CalendarHeart01 from './react/CalendarHeart01'
import CalendarHeart02 from './react/CalendarHeart02'
import CalendarMinus01 from './react/CalendarMinus01'
import CalendarMinus02 from './react/CalendarMinus02'
import CalendarPlus01 from './react/CalendarPlus01'
import CalendarPlus02 from './react/CalendarPlus02'
import Camera01 from './react/Camera01'
import Camera02 from './react/Camera02'
import Camera03 from './react/Camera03'
import CameraLens from './react/CameraLens'
import CameraOff from './react/CameraOff'
import CameraPlus from './react/CameraPlus'
import Certificate01 from './react/Certificate01'
import Certificate02 from './react/Certificate02'
import ChartBreakoutCircle from './react/ChartBreakoutCircle'
import ChartBreakoutSquare from './react/ChartBreakoutSquare'
import ChatRobot from './react/ChatRobot'
import Check from './react/Check'
import CheckCircle from './react/CheckCircle'
import CheckCirclebroken from './react/CheckCirclebroken'
import CheckDone01 from './react/CheckDone01'
import CheckDone02 from './react/CheckDone02'
import CheckHeart from './react/CheckHeart'
import CheckSquare from './react/CheckSquare'
import CheckSquareBroken from './react/CheckSquareBroken'
import CheckVerified01 from './react/CheckVerified01'
import CheckVerified02 from './react/CheckVerified02'
import CheckVerified03 from './react/CheckVerified03'
import ChevronDown from './react/ChevronDown'
import ChevronDownDouble from './react/ChevronDownDouble'
import ChevronDownFill from './react/ChevronDownFill'
import ChevronLeft from './react/ChevronLeft'
import ChevronLeftDouble from './react/ChevronLeftDouble'
import ChevronRight from './react/ChevronRight'
import ChevronRightDouble from './react/ChevronRightDouble'
import ChevronRightFill from './react/ChevronRightFill'
import ChevronSelectorHorizontal from './react/ChevronSelectorHorizontal'
import ChevronSelectorVertical from './react/ChevronSelectorVertical'
import ChevronUp from './react/ChevronUp'
import ChevronUpDouble from './react/ChevronUpDouble'
import ChevronVerticalExpand from './react/ChevronVerticalExpand'
import ChevronVerticalShrink from './react/ChevronVerticalShrink'
import ChromeCast from './react/ChromeCast'
import Circle from './react/Circle'
import CircleCut from './react/CircleCut'
import Clapperboard from './react/Clapperboard'
import Clipboard from './react/Clipboard'
import ClipboardAttachment from './react/ClipboardAttachment'
import ClipboardCheck from './react/ClipboardCheck'
import ClipboardDownload from './react/ClipboardDownload'
import ClipboardMinus from './react/ClipboardMinus'
import ClipboardPlus from './react/ClipboardPlus'
import ClipboardX from './react/ClipboardX'
import Clock from './react/Clock'
import ClockCheck from './react/ClockCheck'
import ClockFastForward from './react/ClockFastForward'
import ClockPlus from './react/ClockPlus'
import ClockRefresh from './react/ClockRefresh'
import ClockRewind from './react/ClockRewind'
import ClockSnooze from './react/ClockSnooze'
import ClockStopwatch from './react/ClockStopwatch'
import Cloud01 from './react/Cloud01'
import Cloud02 from './react/Cloud02'
import Cloud03 from './react/Cloud03'
import CloudBlank01 from './react/CloudBlank01'
import CloudBlank02 from './react/CloudBlank02'
import CloudLightning from './react/CloudLightning'
import CloudMoon from './react/CloudMoon'
import CloudOff from './react/CloudOff'
import CloudRaining01 from './react/CloudRaining01'
import CloudRaining02 from './react/CloudRaining02'
import CloudRaining03 from './react/CloudRaining03'
import CloudRaining04 from './react/CloudRaining04'
import CloudRaining05 from './react/CloudRaining05'
import CloudRaining06 from './react/CloudRaining06'
import CloudSnowing01 from './react/CloudSnowing01'
import CloudSnowing02 from './react/CloudSnowing02'
import CloudSun01 from './react/CloudSun01'
import CloudSun02 from './react/CloudSun02'
import CloudSun03 from './react/CloudSun03'
import Code01 from './react/Code01'
import Code02 from './react/Code02'
import CodeBrowser from './react/CodeBrowser'
import CodeCircle01 from './react/CodeCircle01'
import CodeCircle02 from './react/CodeCircle02'
import CodeCircle03 from './react/CodeCircle03'
import Codepen from './react/Codepen'
import CodeSnippet01 from './react/CodeSnippet01'
import CodeSnippet02 from './react/CodeSnippet02'
import CodeSquare01 from './react/CodeSquare01'
import CodeSquare02 from './react/CodeSquare02'
import Coins01 from './react/Coins01'
import Coins02 from './react/Coins02'
import Coins03 from './react/Coins03'
import Coins04 from './react/Coins04'
import CoinsHand from './react/CoinsHand'
import CoinsStacked01 from './react/CoinsStacked01'
import CoinsStacked02 from './react/CoinsStacked02'
import CoinsStacked03 from './react/CoinsStacked03'
import CoinsStacked04 from './react/CoinsStacked04'
import CoinsSwap01 from './react/CoinsSwap01'
import CoinsSwap02 from './react/CoinsSwap02'
import Collapse08 from './react/Collapse08'
import Colors from './react/Colors'
import Colors1 from './react/Colors1'
import Columns01 from './react/Columns01'
import Columns02 from './react/Columns02'
import Columns03 from './react/Columns03'
import Command from './react/Command'
import Compass from './react/Compass'
import Compass01 from './react/Compass01'
import Compass02 from './react/Compass02'
import Compass03 from './react/Compass03'
import Connect from './react/Connect'
import Container from './react/Container'
import Contrast01 from './react/Contrast01'
import Contrast02 from './react/Contrast02'
import Contrast03 from './react/Contrast03'
import Copy01 from './react/Copy01'
import Copy02 from './react/Copy02'
import Copy03 from './react/Copy03'
import Copy04 from './react/Copy04'
import Copy05 from './react/Copy05'
import Copy06 from './react/Copy06'
import Copy07 from './react/Copy07'
import CornerDownLeft from './react/CornerDownLeft'
import CornerDownRight from './react/CornerDownRight'
import CornerLeftDown from './react/CornerLeftDown'
import CornerLeftUp from './react/CornerLeftUp'
import CornerRightDown from './react/CornerRightDown'
import CornerRightUp from './react/CornerRightUp'
import CornerUpLeft from './react/CornerUpLeft'
import CornerUpRight from './react/CornerUpRight'
import CpuChip01 from './react/CpuChip01'
import CpuChip02 from './react/CpuChip02'
import CreditCard01 from './react/CreditCard01'
import CreditCard02 from './react/CreditCard02'
import CreditCardCheck from './react/CreditCardCheck'
import CreditCardDown from './react/CreditCardDown'
import CreditCardDownload from './react/CreditCardDownload'
import CreditCardEdit from './react/CreditCardEdit'
import CreditCardLock from './react/CreditCardLock'
import CreditCardMinus from './react/CreditCardMinus'
import CreditCardPlus from './react/CreditCardPlus'
import CreditCardRefresh from './react/CreditCardRefresh'
import CreditCardSearch from './react/CreditCardSearch'
import CreditCardShield from './react/CreditCardShield'
import CreditCardUp from './react/CreditCardUp'
import CreditCardUpload from './react/CreditCardUpload'
import CreditCardX from './react/CreditCardX'
import Crop01 from './react/Crop01'
import Crop02 from './react/Crop02'
import Cryptocurrency01 from './react/Cryptocurrency01'
import Cryptocurrency02 from './react/Cryptocurrency02'
import Cryptocurrency03 from './react/Cryptocurrency03'
import Cryptocurrency04 from './react/Cryptocurrency04'
import Cube01 from './react/Cube01'
import Cube02 from './react/Cube02'
import Cube03 from './react/Cube03'
import Cube04 from './react/Cube04'
import CubeOutline from './react/CubeOutline'
import CurrencyBitcoin from './react/CurrencyBitcoin'
import CurrencyBitcoinCircle from './react/CurrencyBitcoinCircle'
import CurrencyDollar from './react/CurrencyDollar'
import CurrencyDollarCircle from './react/CurrencyDollarCircle'
import CurrencyEthereum from './react/CurrencyEthereum'
import CurrencyEthereumCircle from './react/CurrencyEthereumCircle'
import CurrencyEuro from './react/CurrencyEuro'
import CurrencyEuroCircle from './react/CurrencyEuroCircle'
import CurrencyPound from './react/CurrencyPound'
import CurrencyPoundCircle from './react/CurrencyPoundCircle'
import CurrencyRuble from './react/CurrencyRuble'
import CurrencyRubleCircle from './react/CurrencyRubleCircle'
import CurrencyRupee from './react/CurrencyRupee'
import CurrencyRupeeCircle from './react/CurrencyRupeeCircle'
import CurrencyYen from './react/CurrencyYen'
import CurrencyYenCircle from './react/CurrencyYenCircle'
import Cursor01 from './react/Cursor01'
import Cursor02 from './react/Cursor02'
import Cursor03 from './react/Cursor03'
import Cursor04 from './react/Cursor04'
import CursorBox from './react/CursorBox'
import CursorClick01 from './react/CursorClick01'
import CursorClick02 from './react/CursorClick02'
import Data from './react/Data'
import DataApiSystem from './react/DataApiSystem'
import Database from './react/Database'
import Database01 from './react/Database01'
import Database02 from './react/Database02'
import Database03 from './react/Database03'
import DatabseTable from './react/DatabseTable'
import Dataflow01 from './react/Dataflow01'
import Dataflow02 from './react/Dataflow02'
import Dataflow03 from './react/Dataflow03'
import Dataflow04 from './react/Dataflow04'
import DataService from './react/DataService'
import DataServiceAdd from './react/DataServiceAdd'
import Delete from './react/Delete'
import Diamond01 from './react/Diamond01'
import Diamond02 from './react/Diamond02'
import Dice1 from './react/Dice1'
import Dice2 from './react/Dice2'
import Dice3 from './react/Dice3'
import Dice4 from './react/Dice4'
import Dice5 from './react/Dice5'
import Dice6 from './react/Dice6'
import Disc01 from './react/Disc01'
import Disc02 from './react/Disc02'
import DistributeSpacingHorizontal from './react/DistributeSpacingHorizontal'
import DistributeSpacingVertical from './react/DistributeSpacingVertical'
import Divide01 from './react/Divide01'
import Divide02 from './react/Divide02'
import Divide03 from './react/Divide03'
import Divider from './react/Divider'
import DotPoints01 from './react/DotPoints01'
import Dotpoints02 from './react/Dotpoints02'
import DotsGrid from './react/DotsGrid'
import DotsHorizontal from './react/DotsHorizontal'
import DotsVertical from './react/DotsVertical'
import Download01 from './react/Download01'
import Download02 from './react/Download02'
import Download03 from './react/Download03'
import Download04 from './react/Download04'
import DownloadCloud01 from './react/DownloadCloud01'
import DownloadCloud02 from './react/DownloadCloud02'
import DragIn from './react/DragIn'
import Drop from './react/Drop'
import Droplets01 from './react/Droplets01'
import Droplets02 from './react/Droplets02'
import Droplets03 from './react/Droplets03'
import Dropper from './react/Dropper'
import Edit01 from './react/Edit01'
import Edit02 from './react/Edit02'
import Edit03 from './react/Edit03'
import Edit04 from './react/Edit04'
import Edit05 from './react/Edit05'
import Equal from './react/Equal'
import EqualNot from './react/EqualNot'
import Eraser from './react/Eraser'
import Expand01 from './react/Expand01'
import Expand02 from './react/Expand02'
import Expand03 from './react/Expand03'
import Expand04 from './react/Expand04'
import Expand05 from './react/Expand05'
import Expand06 from './react/Expand06'
import Expand08 from './react/Expand08'
import Eye from './react/Eye'
import EyeOff from './react/EyeOff'
import FaceContent from './react/FaceContent'
import FaceFrown from './react/FaceFrown'
import FaceHappy from './react/FaceHappy'
import FaceId from './react/FaceId'
import FaceIdSquare from './react/FaceIdSquare'
import FaceNeutral from './react/FaceNeutral'
import FaceSad from './react/FaceSad'
import FaceSmile from './react/FaceSmile'
import FaceWink from './react/FaceWink'
import FastBackward from './react/FastBackward'
import FastForward from './react/FastForward'
import Feather from './react/Feather'
import Figma from './react/Figma'
import File01 from './react/File01'
import File02 from './react/File02'
import File03 from './react/File03'
import File04 from './react/File04'
import File05 from './react/File05'
import File06 from './react/File06'
import File07 from './react/File07'
import FileAttachment01 from './react/FileAttachment01'
import FileAttachment02 from './react/FileAttachment02'
import FileAttachment03 from './react/FileAttachment03'
import FileAttachment04 from './react/FileAttachment04'
import FileAttachment05 from './react/FileAttachment05'
import FileCheck01 from './react/FileCheck01'
import FileCheck02 from './react/FileCheck02'
import FileCheck03 from './react/FileCheck03'
import FileCode01 from './react/FileCode01'
import FileCode02 from './react/FileCode02'
import FileDownload01 from './react/FileDownload01'
import FileDownload02 from './react/FileDownload02'
import FileDownload03 from './react/FileDownload03'
import FileHeart01 from './react/FileHeart01'
import FileHeart02 from './react/FileHeart02'
import FileHeart03 from './react/FileHeart03'
import FileImport02 from './react/FileImport02'
import FileLock01 from './react/FileLock01'
import FileLock02 from './react/FileLock02'
import FileLock03 from './react/FileLock03'
import FileMinus01 from './react/FileMinus01'
import FileMinus02 from './react/FileMinus02'
import FileMinus03 from './react/FileMinus03'
import FilePlus01 from './react/FilePlus01'
import FilePlus02 from './react/FilePlus02'
import FilePlus03 from './react/FilePlus03'
import FileQuestion01 from './react/FileQuestion01'
import FileQuestion02 from './react/FileQuestion02'
import FileQuestion03 from './react/FileQuestion03'
import FileSearch01 from './react/FileSearch01'
import FileSearch02 from './react/FileSearch02'
import FileSearch03 from './react/FileSearch03'
import FileShield01 from './react/FileShield01'
import FileShield02 from './react/FileShield02'
import FileShield03 from './react/FileShield03'
import FileX01 from './react/FileX01'
import FileX02 from './react/FileX02'
import FileX03 from './react/FileX03'
import Film01 from './react/Film01'
import Film02 from './react/Film02'
import Film03 from './react/Film03'
import FilterFunnel01 from './react/FilterFunnel01'
import FilterFunnel02 from './react/FilterFunnel02'
import FilterLines from './react/FilterLines'
import Fingerprint01 from './react/Fingerprint01'
import Fingerprint02 from './react/Fingerprint02'
import Fingerprint03 from './react/Fingerprint03'
import Fingerprint04 from './react/Fingerprint04'
import Flag01 from './react/Flag01'
import Flag02 from './react/Flag02'
import Flag03 from './react/Flag03'
import Flag04 from './react/Flag04'
import Flag05 from './react/Flag05'
import Flag06 from './react/Flag06'
import Flash from './react/Flash'
import FlashOff from './react/FlashOff'
import FlexAlignBottom from './react/FlexAlignBottom'
import FlexAlignLeft from './react/FlexAlignLeft'
import FlexAlignRight from './react/FlexAlignRight'
import FlexAlignTop from './react/FlexAlignTop'
import FlipBackward from './react/FlipBackward'
import FlipForward from './react/FlipForward'
import Folder from './react/Folder'
import FolderCheck from './react/FolderCheck'
import FolderClosed from './react/FolderClosed'
import FolderCode from './react/FolderCode'
import FolderDownload from './react/FolderDownload'
import FolderLock from './react/FolderLock'
import FolderMinus from './react/FolderMinus'
import FolderPlus from './react/FolderPlus'
import FolderQuestion from './react/FolderQuestion'
import FolderSearch from './react/FolderSearch'
import FolderSettings from './react/FolderSettings'
import FolderShield from './react/FolderShield'
import FolderX from './react/FolderX'
import Framer from './react/Framer'
import GamingPad01 from './react/GamingPad01'
import GamingPad02 from './react/GamingPad02'
import Gift01 from './react/Gift01'
import Gift02 from './react/Gift02'
import GitBranch01 from './react/GitBranch01'
import GitBranch02 from './react/GitBranch02'
import GitCommit from './react/GitCommit'
import Github from './react/Github'
import GitMerge from './react/GitMerge'
import GitPullRequest from './react/GitPullRequest'
import Glasses01 from './react/Glasses01'
import Glasses02 from './react/Glasses02'
import Globe01 from './react/Globe01'
import Globe011 from './react/Globe011'
import Globe02 from './react/Globe02'
import Globe021 from './react/Globe021'
import Globe03 from './react/Globe03'
import Globe04 from './react/Globe04'
import Globe05 from './react/Globe05'
import Globe06 from './react/Globe06'
import GoogleChrome from './react/GoogleChrome'
import GraduationHat01 from './react/GraduationHat01'
import GraduationHat02 from './react/GraduationHat02'
import Grid01 from './react/Grid01'
import Grid02 from './react/Grid02'
import Grid03 from './react/Grid03'
import GridDotsBlank from './react/GridDotsBlank'
import GridDotsBottom from './react/GridDotsBottom'
import GridDotsHorizontalCenter from './react/GridDotsHorizontalCenter'
import GridDotsLeft from './react/GridDotsLeft'
import GridDotsOuter from './react/GridDotsOuter'
import GridDotsRight from './react/GridDotsRight'
import GridDotsTop from './react/GridDotsTop'
import GridDotsVerticalCenter from './react/GridDotsVerticalCenter'
import Hand from './react/Hand'
import HandsDown from './react/HandsDown'
import HandsDownFill from './react/HandsDownFill'
import HandsUp from './react/HandsUp'
import HandsUpFill from './react/HandsUpFill'
import HardDrive from './react/HardDrive'
import Hash01 from './react/Hash01'
import Hash02 from './react/Hash02'
import Heading01 from './react/Heading01'
import Heading02 from './react/Heading02'
import HeadingSquare from './react/HeadingSquare'
import Headphones01 from './react/Headphones01'
import Headphones02 from './react/Headphones02'
import Heart from './react/Heart'
import HeartCircle from './react/HeartCircle'
import HeartHand from './react/HeartHand'
import HeartHexagon from './react/HeartHexagon'
import HeartOctagon from './react/HeartOctagon'
import HeartRounded from './react/HeartRounded'
import Hearts from './react/Hearts'
import HeartSquare from './react/HeartSquare'
import HelpCircle from './react/HelpCircle'
import HelpOctagon from './react/HelpOctagon'
import HelpSquare from './react/HelpSquare'
import Hexagon01 from './react/Hexagon01'
import Hexagon02 from './react/Hexagon02'
import Home01 from './react/Home01'
import Home02 from './react/Home02'
import Home03 from './react/Home03'
import Home04 from './react/Home04'
import Home05 from './react/Home05'
import HomeLine from './react/HomeLine'
import HomeSmile from './react/HomeSmile'
import HorizontalBarChart01 from './react/HorizontalBarChart01'
import HorizontalBarChart02 from './react/HorizontalBarChart02'
import HorizontalBarChart03 from './react/HorizontalBarChart03'
import Hourglass01 from './react/Hourglass01'
import Hourglass02 from './react/Hourglass02'
import Hourglass03 from './react/Hourglass03'
import Hurricane01 from './react/Hurricane01'
import Hurricane02 from './react/Hurricane02'
import Hurricane03 from './react/Hurricane03'
import Image01 from './react/Image01'
import Image02 from './react/Image02'
import Image03 from './react/Image03'
import Image04 from './react/Image04'
import Image05 from './react/Image05'
import ImageCheck from './react/ImageCheck'
import ImageDown from './react/ImageDown'
import ImageIndentLeft from './react/ImageIndentLeft'
import ImageIndentRight from './react/ImageIndentRight'
import ImageLeft from './react/ImageLeft'
import ImagePlus from './react/ImagePlus'
import ImageRight from './react/ImageRight'
import ImageUp from './react/ImageUp'
import ImageUser from './react/ImageUser'
import ImageUserCheck from './react/ImageUserCheck'
import ImageUserDown from './react/ImageUserDown'
import ImageUserLeft from './react/ImageUserLeft'
import ImageUserPlus from './react/ImageUserPlus'
import ImageUserRight from './react/ImageUserRight'
import ImageUserUp from './react/ImageUserUp'
import ImageUserX from './react/ImageUserX'
import ImageX from './react/ImageX'
import Inbox01 from './react/Inbox01'
import Inbox02 from './react/Inbox02'
import Infinity from './react/Infinity'
import Info2 from './react/Info2'
import InfoCircle from './react/InfoCircle'
import InfoHexagon from './react/InfoHexagon'
import InfoOctagon from './react/InfoOctagon'
import InfoSquare from './react/InfoSquare'
import IntersectCircle from './react/IntersectCircle'
import IntersectSquare from './react/IntersectSquare'
import Italic01 from './react/Italic01'
import Italic02 from './react/Italic02'
import ItalicSquare from './react/ItalicSquare'
import Key01 from './react/Key01'
import Key02 from './react/Key02'
import Keyboard01 from './react/Keyboard01'
import Keyboard02 from './react/Keyboard02'
import Laptop01 from './react/Laptop01'
import Laptop02 from './react/Laptop02'
import LayerSingle from './react/LayerSingle'
import LayersThree01 from './react/LayersThree01'
import LayersThree02 from './react/LayersThree02'
import LayersTwo01 from './react/LayersTwo01'
import LayersTwo02 from './react/LayersTwo02'
import LaygroundGrid02 from './react/LaygroundGrid02'
import LayoutAlt01 from './react/LayoutAlt01'
import LayoutAlt02 from './react/LayoutAlt02'
import LayoutAlt03 from './react/LayoutAlt03'
import LayoutAlt04 from './react/LayoutAlt04'
import LayoutBottom from './react/LayoutBottom'
import LayoutBottomFill from './react/LayoutBottomFill'
import LayoutGrid01 from './react/LayoutGrid01'
import LayoutGrid02 from './react/LayoutGrid02'
import LayoutLeft from './react/LayoutLeft'
import LayoutLeftFill from './react/LayoutLeftFill'
import LayoutRight from './react/LayoutRight'
import LayoutRightFill from './react/LayoutRightFill'
import LayoutTop from './react/LayoutTop'
import LayoutTopFill from './react/LayoutTopFill'
import LeftIndent01 from './react/LeftIndent01'
import LeftIndent02 from './react/LeftIndent02'
import LetterSpacing01 from './react/LetterSpacing01'
import LetterSpacing02 from './react/LetterSpacing02'
import LifeBuoy01 from './react/LifeBuoy01'
import LifeBuoy02 from './react/LifeBuoy02'
import Lightbulb01 from './react/Lightbulb01'
import Lightbulb02 from './react/Lightbulb02'
import Lightbulb03 from './react/Lightbulb03'
import Lightbulb04 from './react/Lightbulb04'
import Lightbulb05 from './react/Lightbulb05'
import Lightning01 from './react/Lightning01'
import Lightning02 from './react/Lightning02'
import LineChart from './react/LineChart'
import LineChartDown01 from './react/LineChartDown01'
import LineChartDown02 from './react/LineChartDown02'
import LineChartDown03 from './react/LineChartDown03'
import LineChartDown04 from './react/LineChartDown04'
import LineChartDown05 from './react/LineChartDown05'
import LineChartUp01 from './react/LineChartUp01'
import LineChartUp02 from './react/LineChartUp02'
import LineChartUp03 from './react/LineChartUp03'
import LineChartUp04 from './react/LineChartUp04'
import LineChartUp05 from './react/LineChartUp05'
import LineHeight from './react/LineHeight'
import Link01 from './react/Link01'
import Link02 from './react/Link02'
import Link03 from './react/Link03'
import Link04 from './react/Link04'
import Link05 from './react/Link05'
import LinkBroken01 from './react/LinkBroken01'
import LinkBroken02 from './react/LinkBroken02'
import LinkExternal01 from './react/LinkExternal01'
import LinkExternal02 from './react/LinkExternal02'
import List from './react/List'
import Loading01 from './react/Loading01'
import Loading02 from './react/Loading02'
import Loading03 from './react/Loading03'
import Lock01 from './react/Lock01'
import Lock02 from './react/Lock02'
import Lock03 from './react/Lock03'
import Lock04 from './react/Lock04'
import LockKeyholeCircle from './react/LockKeyholeCircle'
import LockKeyholeSquare from './react/LockKeyholeSquare'
import LockUnlocked01 from './react/LockUnlocked01'
import LockUnlocked02 from './react/LockUnlocked02'
import LockUnlocked03 from './react/LockUnlocked03'
import LockUnlocked04 from './react/LockUnlocked04'
import LogIn01 from './react/LogIn01'
import LogIn02 from './react/LogIn02'
import LogIn03 from './react/LogIn03'
import LogIn04 from './react/LogIn04'
import LogOut01 from './react/LogOut01'
import LogOut02 from './react/LogOut02'
import LogOut03 from './react/LogOut03'
import LogOut04 from './react/LogOut04'
import Luggage01 from './react/Luggage01'
import Luggage02 from './react/Luggage02'
import Luggage03 from './react/Luggage03'
import MagicWand01 from './react/MagicWand01'
import MagicWand02 from './react/MagicWand02'
import Mail01 from './react/Mail01'
import Mail02 from './react/Mail02'
import Mail03 from './react/Mail03'
import Mail04 from './react/Mail04'
import Mail05 from './react/Mail05'
import Map01 from './react/Map01'
import Map02 from './react/Map02'
import Mark from './react/Mark'
import MarkerPin01 from './react/MarkerPin01'
import MarkerPin02 from './react/MarkerPin02'
import MarkerPin03 from './react/MarkerPin03'
import MarkerPin04 from './react/MarkerPin04'
import MarkerPin05 from './react/MarkerPin05'
import MarkerPin06 from './react/MarkerPin06'
import Maximize01 from './react/Maximize01'
import Maximize02 from './react/Maximize02'
import MediaGithub from './react/MediaGithub'
import MediaGithubFill from './react/MediaGithubFill'
import MediaGoogle from './react/MediaGoogle'
import MediaMicrosoft from './react/MediaMicrosoft'
import MedicalCircle from './react/MedicalCircle'
import MedicalCross from './react/MedicalCross'
import MedicalSquare from './react/MedicalSquare'
import Menu01 from './react/Menu01'
import Menu02 from './react/Menu02'
import Menu03 from './react/Menu03'
import Menu04 from './react/Menu04'
import Menu05 from './react/Menu05'
import MenuLeft from './react/MenuLeft'
import MenuRight from './react/MenuRight'
import MessageAlertCircle from './react/MessageAlertCircle'
import MessageAlertSquare from './react/MessageAlertSquare'
import MessageChatCircle from './react/MessageChatCircle'
import MessageChatSquare from './react/MessageChatSquare'
import MessageCheckCircle from './react/MessageCheckCircle'
import MessageCheckSquare from './react/MessageCheckSquare'
import MessageCircle01 from './react/MessageCircle01'
import MessageCircle02 from './react/MessageCircle02'
import MessageDotsCircle from './react/MessageDotsCircle'
import MessageDotsSquare from './react/MessageDotsSquare'
import MessageHeartCircle from './react/MessageHeartCircle'
import MessageHeartSquare from './react/MessageHeartSquare'
import MessageNotificationCircle from './react/MessageNotificationCircle'
import MessageNotificationSquare from './react/MessageNotificationSquare'
import MessagePlusCircle from './react/MessagePlusCircle'
import MessagePlusSquare from './react/MessagePlusSquare'
import MessageQuestionCircle from './react/MessageQuestionCircle'
import MessageQuestionSquare from './react/MessageQuestionSquare'
import MessageSmileCircle from './react/MessageSmileCircle'
import MessageSmileSquare from './react/MessageSmileSquare'
import MessageSquare01 from './react/MessageSquare01'
import MessageSquare02 from './react/MessageSquare02'
import MessageTextCircle01 from './react/MessageTextCircle01'
import MessageTextCircle02 from './react/MessageTextCircle02'
import MessageTextSquare01 from './react/MessageTextSquare01'
import MessageTextSquare02 from './react/MessageTextSquare02'
import MessageXCircle from './react/MessageXCircle'
import MessageXSquare from './react/MessageXSquare'
import Microphone01 from './react/Microphone01'
import Microphone02 from './react/Microphone02'
import MicrophoneOff01 from './react/MicrophoneOff01'
import MicrophoneOff02 from './react/MicrophoneOff02'
import Microscope from './react/Microscope'
import Minimize01 from './react/Minimize01'
import Minimize02 from './react/Minimize02'
import Minus from './react/Minus'
import MinusCircle from './react/MinusCircle'
import MinusSquare from './react/MinusSquare'
import Modem01 from './react/Modem01'
import Modem02 from './react/Modem02'
import Monitor01 from './react/Monitor01'
import Monitor02 from './react/Monitor02'
import Monitor03 from './react/Monitor03'
import Monitor04 from './react/Monitor04'
import Monitor05 from './react/Monitor05'
import Moon01 from './react/Moon01'
import Moon02 from './react/Moon02'
import MoonEclipse from './react/MoonEclipse'
import MoonStar from './react/MoonStar'
import Mouse from './react/Mouse'
import Move from './react/Move'
import MusicNote01 from './react/MusicNote01'
import MusicNote02 from './react/MusicNote02'
import MusicNotePlus from './react/MusicNotePlus'
import NavigationPointer01 from './react/NavigationPointer01'
import NavigationPointer02 from './react/NavigationPointer02'
import NavigationPointerOff01 from './react/NavigationPointerOff01'
import NavigationPointerOff02 from './react/NavigationPointerOff02'
import NotificationBox from './react/NotificationBox'
import NotificationMessage from './react/NotificationMessage'
import NotificationText from './react/NotificationText'
import Numberic from './react/Numberic'
import Octagon from './react/Octagon'
import OpenAi from './react/OpenAi'
import OrientationHorizontalFill from './react/OrientationHorizontalFill'
import OrientationVerticalFill from './react/OrientationVerticalFill'
import Package from './react/Package'
import PackageCheck from './react/PackageCheck'
import PackageMinus from './react/PackageMinus'
import PackagePlus from './react/PackagePlus'
import PackageSearch from './react/PackageSearch'
import PackageX from './react/PackageX'
import Paint from './react/Paint'
import PaintPour from './react/PaintPour'
import Palette from './react/Palette'
import Paperclip from './react/Paperclip'
import ParagraphSpacing from './react/ParagraphSpacing'
import ParagraphWrap from './react/ParagraphWrap'
import Passcode from './react/Passcode'
import PasscodeLock from './react/PasscodeLock'
import Passport from './react/Passport'
import PauseCircle from './react/PauseCircle'
import PauseSquare from './react/PauseSquare'
import Pencil01 from './react/Pencil01'
import Pencil02 from './react/Pencil02'
import PencilLine from './react/PencilLine'
import Pentagon from './react/Pentagon'
import PenTool01 from './react/PenTool01'
import PenTool02 from './react/PenTool02'
import PenToolMinus from './react/PenToolMinus'
import PenToolPlus from './react/PenToolPlus'
import Percent01 from './react/Percent01'
import Percent02 from './react/Percent02'
import Percent03 from './react/Percent03'
import Perspective01 from './react/Perspective01'
import Perspective02 from './react/Perspective02'
import Phone from './react/Phone'
import Phone01 from './react/Phone01'
import Phone02 from './react/Phone02'
import PhoneCall01 from './react/PhoneCall01'
import PhoneCall02 from './react/PhoneCall02'
import PhoneHangUp from './react/PhoneHangUp'
import PhoneIncoming01 from './react/PhoneIncoming01'
import PhoneIncoming02 from './react/PhoneIncoming02'
import PhoneOutgoing01 from './react/PhoneOutgoing01'
import PhoneOutgoing02 from './react/PhoneOutgoing02'
import PhonePause from './react/PhonePause'
import PhonePlus from './react/PhonePlus'
import PhoneX from './react/PhoneX'
import PieChart01 from './react/PieChart01'
import PieChart02 from './react/PieChart02'
import PieChart03 from './react/PieChart03'
import PieChart04 from './react/PieChart04'
import PiggyBank01 from './react/PiggyBank01'
import PiggyBank02 from './react/PiggyBank02'
import Pilcrow01 from './react/Pilcrow01'
import Pilcrow02 from './react/Pilcrow02'
import PilcrowSquare from './react/PilcrowSquare'
import Pin01 from './react/Pin01'
import Pin02 from './react/Pin02'
import Placeholder from './react/Placeholder'
import Plane from './react/Plane'
import Play from './react/Play'
import PlayCircle from './react/PlayCircle'
import PlaySquare from './react/PlaySquare'
import Plus from './react/Plus'
import PlusCircle from './react/PlusCircle'
import PlusSquare from './react/PlusSquare'
import Podcast from './react/Podcast'
import Power01 from './react/Power01'
import Power02 from './react/Power02'
import Power03 from './react/Power03'
import PresentationChart01 from './react/PresentationChart01'
import PresentationChart02 from './react/PresentationChart02'
import PresentationChart03 from './react/PresentationChart03'
import Printer from './react/Printer'
import PuzzlePiece01 from './react/PuzzlePiece01'
import PuzzlePiece02 from './react/PuzzlePiece02'
import QrCode01 from './react/QrCode01'
import QrCode02 from './react/QrCode02'
import Question from './react/Question'
import Receipt from './react/Receipt'
import ReceiptCheck from './react/ReceiptCheck'
import Recording01 from './react/Recording01'
import Recording02 from './react/Recording02'
import Recording03 from './react/Recording03'
import Redeploy from './react/Redeploy'
import Reflect01 from './react/Reflect01'
import Reflect02 from './react/Reflect02'
import RefreshCcw01 from './react/RefreshCcw01'
import RefreshCcw02 from './react/RefreshCcw02'
import RefreshCcw03 from './react/RefreshCcw03'
import RefreshCcw04 from './react/RefreshCcw04'
import RefreshCcw05 from './react/RefreshCcw05'
import RefreshCw01 from './react/RefreshCw01'
import RefreshCw02 from './react/RefreshCw02'
import RefreshCw03 from './react/RefreshCw03'
import RefreshCw04 from './react/RefreshCw04'
import RefreshCw05 from './react/RefreshCw05'
import Repeat01 from './react/Repeat01'
import Repeat02 from './react/Repeat02'
import Repeat03 from './react/Repeat03'
import Repeat04 from './react/Repeat04'
import ReverseLeft from './react/ReverseLeft'
import ReverseRight from './react/ReverseRight'
import Right from './react/Right'
import RightIndent01 from './react/RightIndent01'
import RightIndent02 from './react/RightIndent02'
import Rocket01 from './react/Rocket01'
import Rocket02 from './react/Rocket02'
import RollerBrush from './react/RollerBrush'
import Route from './react/Route'
import Rows01 from './react/Rows01'
import Rows02 from './react/Rows02'
import Rows03 from './react/Rows03'
import Rss01 from './react/Rss01'
import Rss02 from './react/Rss02'
import Ruler from './react/Ruler'
import Run from './react/Run'
import RunFill from './react/RunFill'
import Safe from './react/Safe'
import Sale01 from './react/Sale01'
import Sale02 from './react/Sale02'
import Sale03 from './react/Sale03'
import Sale04 from './react/Sale04'
import Save01 from './react/Save01'
import Save02 from './react/Save02'
import Save03 from './react/Save03'
import Scale01 from './react/Scale01'
import Scale02 from './react/Scale02'
import Scale03 from './react/Scale03'
import Scales01 from './react/Scales01'
import Scales02 from './react/Scales02'
import Scan from './react/Scan'
import Scissors01 from './react/Scissors01'
import Scissors02 from './react/Scissors02'
import ScissorsCut01 from './react/ScissorsCut01'
import ScissorsCut02 from './react/ScissorsCut02'
import SearchLg from './react/SearchLg'
import SearchMd from './react/SearchMd'
import SearchRefraction from './react/SearchRefraction'
import SearchSm from './react/SearchSm'
import SeeMore from './react/SeeMore'
import SeeShort from './react/SeeShort'
import Send01 from './react/Send01'
import Send02 from './react/Send02'
import Send03 from './react/Send03'
import Series from './react/Series'
import Server01 from './react/Server01'
import Server02 from './react/Server02'
import Server03 from './react/Server03'
import Server04 from './react/Server04'
import Server05 from './react/Server05'
import Server06 from './react/Server06'
import Service from './react/Service'
import Settings01 from './react/Settings01'
import Settings02 from './react/Settings02'
import Settings03 from './react/Settings03'
import Settings04 from './react/Settings04'
import Share01 from './react/Share01'
import Share02 from './react/Share02'
import Share03 from './react/Share03'
import Share04 from './react/Share04'
import Share05 from './react/Share05'
import Share06 from './react/Share06'
import Share07 from './react/Share07'
import Shield01 from './react/Shield01'
import Shield02 from './react/Shield02'
import Shield03 from './react/Shield03'
import ShieldDollar from './react/ShieldDollar'
import ShieldOff from './react/ShieldOff'
import ShieldPlus from './react/ShieldPlus'
import ShieldTick from './react/ShieldTick'
import ShieldUser from './react/ShieldUser'
import ShieldZap from './react/ShieldZap'
import ShoppingBag01 from './react/ShoppingBag01'
import ShoppingBag02 from './react/ShoppingBag02'
import ShoppingBag03 from './react/ShoppingBag03'
import ShoppingCart01 from './react/ShoppingCart01'
import ShoppingCart02 from './react/ShoppingCart02'
import ShoppingCart03 from './react/ShoppingCart03'
import Shuffle01 from './react/Shuffle01'
import Shuffle02 from './react/Shuffle02'
import Signal01 from './react/Signal01'
import Signal02 from './react/Signal02'
import Signal03 from './react/Signal03'
import Simcard from './react/Simcard'
import Skew from './react/Skew'
import SkipBack from './react/SkipBack'
import SkipForward from './react/SkipForward'
import SlashCircle01 from './react/SlashCircle01'
import SlashCircle02 from './react/SlashCircle02'
import SlashDivider from './react/SlashDivider'
import SlashOctagon from './react/SlashOctagon'
import Sliders01 from './react/Sliders01'
import Sliders02 from './react/Sliders02'
import Sliders03 from './react/Sliders03'
import Sliders04 from './react/Sliders04'
import Snowflake01 from './react/Snowflake01'
import Snowflake02 from './react/Snowflake02'
import SpacingHeight01 from './react/SpacingHeight01'
import SpacingHeight02 from './react/SpacingHeight02'
import SpacingWidth01 from './react/SpacingWidth01'
import SpacingWidth02 from './react/SpacingWidth02'
import Speaker01 from './react/Speaker01'
import Speaker02 from './react/Speaker02'
import Speaker03 from './react/Speaker03'
import Speedometer01 from './react/Speedometer01'
import Speedometer02 from './react/Speedometer02'
import Speedometer03 from './react/Speedometer03'
import Speedometer04 from './react/Speedometer04'
import Square from './react/Square'
import Stand from './react/Stand'
import Star01 from './react/Star01'
import Star02 from './react/Star02'
import Star03 from './react/Star03'
import Star04 from './react/Star04'
import Star05 from './react/Star05'
import Star06 from './react/Star06'
import Star07 from './react/Star07'
import Stars01 from './react/Stars01'
import Stars02 from './react/Stars02'
import Stars03 from './react/Stars03'
import StickerCircle from './react/StickerCircle'
import StickerSquare from './react/StickerSquare'
import Stop from './react/Stop'
import StopCircle from './react/StopCircle'
import StopSquare from './react/StopSquare'
import Strikethrough01 from './react/Strikethrough01'
import Strikethrough02 from './react/Strikethrough02'
import StrikethroughSquare from './react/StrikethroughSquare'
import String01 from './react/String01'
import Subscript from './react/Subscript'
import Sun from './react/Sun'
import Sunrise from './react/Sunrise'
import Sunset from './react/Sunset'
import SunSetting01 from './react/SunSetting01'
import SunSetting02 from './react/SunSetting02'
import SunSetting03 from './react/SunSetting03'
import SwitchHorizontal01 from './react/SwitchHorizontal01'
import SwitchHorizontal02 from './react/SwitchHorizontal02'
import SwitchVertical01 from './react/SwitchVertical01'
import SwitchVertical02 from './react/SwitchVertical02'
import SystemDatabase from './react/SystemDatabase'
import SystemMode from './react/SystemMode'
import Table from './react/Table'
import Tablet01 from './react/Tablet01'
import Tablet02 from './react/Tablet02'
import Tag01 from './react/Tag01'
import Tag02 from './react/Tag02'
import Tag03 from './react/Tag03'
import Target01 from './react/Target01'
import Target02 from './react/Target02'
import Target03 from './react/Target03'
import Target04 from './react/Target04'
import Target05 from './react/Target05'
import Telescope from './react/Telescope'
import Terminal from './react/Terminal'
import TerminalBrowser from './react/TerminalBrowser'
import TerminalCircle from './react/TerminalCircle'
import TerminalSquare from './react/TerminalSquare'
import TextInput from './react/TextInput'
import Thermometer01 from './react/Thermometer01'
import Thermometer02 from './react/Thermometer02'
import Thermometer03 from './react/Thermometer03'
import ThermometerCold from './react/ThermometerCold'
import ThermometerWarm from './react/ThermometerWarm'
import ThumbsDown from './react/ThumbsDown'
import ThumbsUp from './react/ThumbsUp'
import Ticket01 from './react/Ticket01'
import Ticket02 from './react/Ticket02'
import Toggle01Left from './react/Toggle01Left'
import Toggle01Right from './react/Toggle01Right'
import Toggle02Left from './react/Toggle02Left'
import Toggle02Right from './react/Toggle02Right'
import Toggle03Left from './react/Toggle03Left'
import Toggle03Right from './react/Toggle03Right'
import Tool01 from './react/Tool01'
import Tool02 from './react/Tool02'
import Tools from './react/Tools'
import Train from './react/Train'
import Tram from './react/Tram'
import Transform from './react/Transform'
import Translate01 from './react/Translate01'
import Translate02 from './react/Translate02'
import Trash01 from './react/Trash01'
import Trash02 from './react/Trash02'
import Trash03 from './react/Trash03'
import Trash04 from './react/Trash04'
import TrendDown01 from './react/TrendDown01'
import TrendDown02 from './react/TrendDown02'
import TrendUp01 from './react/TrendUp01'
import TrendUp02 from './react/TrendUp02'
import Triangle from './react/Triangle'
import Trophy01 from './react/Trophy01'
import Trophy02 from './react/Trophy02'
import Truck01 from './react/Truck01'
import Truck02 from './react/Truck02'
import Tv01 from './react/Tv01'
import Tv02 from './react/Tv02'
import Tv03 from './react/Tv03'
import Type01 from './react/Type01'
import Type02 from './react/Type02'
import Types02 from './react/Types02'
import TypeSquare from './react/TypeSquare'
import TypeStrikethrough01 from './react/TypeStrikethrough01'
import TypeStrikethrough02 from './react/TypeStrikethrough02'
import Umbrella01 from './react/Umbrella01'
import Umbrella02 from './react/Umbrella02'
import Umbrella03 from './react/Umbrella03'
import Underline01 from './react/Underline01'
import Underline02 from './react/Underline02'
import UnderlineSquare from './react/UnderlineSquare'
import Upload01 from './react/Upload01'
import Upload02 from './react/Upload02'
import Upload03 from './react/Upload03'
import Upload04 from './react/Upload04'
import UploadCloud01 from './react/UploadCloud01'
import UploadCloud02 from './react/UploadCloud02'
import UsbFlashDrive from './react/UsbFlashDrive'
import User01 from './react/User01'
import User02 from './react/User02'
import User03 from './react/User03'
import UserCheck01 from './react/UserCheck01'
import UserCheck02 from './react/UserCheck02'
import UserCircle from './react/UserCircle'
import UserDown01 from './react/UserDown01'
import UserDown02 from './react/UserDown02'
import UserEdit from './react/UserEdit'
import UserLeft01 from './react/UserLeft01'
import UserLeft02 from './react/UserLeft02'
import UserMinus01 from './react/UserMinus01'
import UserMinus02 from './react/UserMinus02'
import UserPlus01 from './react/UserPlus01'
import UserPlus02 from './react/UserPlus02'
import UserRight01 from './react/UserRight01'
import UserRight02 from './react/UserRight02'
import Users01 from './react/Users01'
import Users02 from './react/Users02'
import Users03 from './react/Users03'
import UsersCheck from './react/UsersCheck'
import UsersDown from './react/UsersDown'
import UsersEdit from './react/UsersEdit'
import UsersLeft from './react/UsersLeft'
import UsersMinus from './react/UsersMinus'
import UsersPlus from './react/UsersPlus'
import UserSquare from './react/UserSquare'
import UsersRight from './react/UsersRight'
import UsersUp from './react/UsersUp'
import UsersX from './react/UsersX'
import UserUp01 from './react/UserUp01'
import UserUp02 from './react/UserUp02'
import UserX01 from './react/UserX01'
import UserX02 from './react/UserX02'
import Variable from './react/Variable'
import VideoRecorder from './react/VideoRecorder'
import VideoRecorderOff from './react/VideoRecorderOff'
import Virus from './react/Virus'
import Voicemail from './react/Voicemail'
import VolumeMax from './react/VolumeMax'
import VolumeMin from './react/VolumeMin'
import VolumeMinus from './react/VolumeMinus'
import VolumePlus from './react/VolumePlus'
import VolumeX from './react/VolumeX'
import Wallet01 from './react/Wallet01'
import Wallet02 from './react/Wallet02'
import Wallet03 from './react/Wallet03'
import Wallet04 from './react/Wallet04'
import Wallet05 from './react/Wallet05'
import WatchCircle from './react/WatchCircle'
import WatchSquare from './react/WatchSquare'
import Waves from './react/Waves'
import Webcam01 from './react/Webcam01'
import Webcam02 from './react/Webcam02'
import Wifi from './react/Wifi'
import WifiOff from './react/WifiOff'
import Wind01 from './react/Wind01'
import Wind02 from './react/Wind02'
import Wind03 from './react/Wind03'
import X from './react/X'
import XAxis from './react/XAxis'
import XCircle from './react/XCircle'
import XClose from './react/XClose'
import XSquare from './react/XSquare'
import YAxis from './react/YAxis'
import Youtube from './react/Youtube'
import Zap from './react/Zap'
import ZapCircle from './react/ZapCircle'
import ZapFast from './react/ZapFast'
import ZapOff from './react/ZapOff'
import ZapSquare from './react/ZapSquare'
import ZoomIn from './react/ZoomIn'
import ZoomOut from './react/ZoomOut'

export const ICON_MAP = {
  Activity,
  ActivityHeart,
  AiExplore01,
  AiMessage,
  Airplay,
  Airpods,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlertCircle,
  AlertHexagon,
  AlertOctagon,
  AlertSquare,
  AlertTriangle,
  AlertTriangleFill,
  AlignBottom01,
  AlignBottom02,
  AlignCenter,
  AlignHorizontalCentre01,
  AlignHorizontalCentre02,
  AlignJustify,
  AlignLeft,
  AlignLeft01,
  AlignLeft02,
  AlignRight,
  AlignRight01,
  AlignRight02,
  AlignTopArrow01,
  AlignTopArrow02,
  AlignVerticalCenter01,
  AlignVerticalCenter02,
  Anchor,
  Annotation,
  AnnotationAlert,
  AnnotationCheck,
  AnnotationDots,
  AnnotationHeart,
  AnnotationInfo,
  AnnotationPlus,
  AnnotationQuestion,
  AnnotationX,
  Announcement01,
  Announcement02,
  Announcement03,
  Archive,
  ArrowBlockDown,
  ArrowBlockLeft,
  ArrowBlockRight,
  ArrowBlockUp,
  ArrowCircleBrokenDown,
  ArrowCircleBrokenDownLeft,
  ArrowCircleBrokenDownRight,
  ArrowCircleBrokenLeft,
  ArrowCircleBrokenRight,
  ArrowCircleBrokenUp,
  ArrowCircleBrokenUpLeft,
  ArrowCircleBrokenUpRight,
  ArrowCircleDown,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowNarrowDown,
  ArrowNarrowDownLeft,
  ArrowNarrowDownRight,
  ArrowNarrowLeft,
  ArrowNarrowRight,
  ArrowNarrowUp,
  ArrowNarrowUpLeft,
  ArrowNarrowUpRight,
  ArrowRight,
  ArrowSquareDown,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareLeft,
  ArrowSquareRight,
  ArrowSquareUp,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowsDown,
  ArrowsLeft,
  ArrowsRight,
  ArrowsTriangle,
  ArrowsUp,
  Asterisk01,
  Asterisk02,
  AtSign,
  Atom01,
  Atom02,
  Attachment01,
  Attachment02,
  Award01,
  Award02,
  Award03,
  Award04,
  Award05,
  Backpack,
  Bank,
  BankNote01,
  BankNote02,
  BankNote03,
  BarChart01,
  BarChart02,
  BarChart03,
  BarChart04,
  BarChart05,
  BarChart06,
  BarChart07,
  BarChart08,
  BarChart09,
  BarChart10,
  BarChart11,
  BarChart12,
  BarChartCircle01,
  BarChartCircle02,
  BarChartCircle03,
  BarChartSquare01,
  BarChartSquare02,
  BarChartSquare03,
  BarChartSquareDown,
  BarChartSquareMinus,
  BarChartSquarePlus,
  BarChartSquareUp,
  BarHorizontal,
  BarLineChart,
  BarVertical,
  BatteryCharging01,
  BatteryCharging02,
  BatteryEmpty,
  BatteryFull,
  BatteryLow,
  BatteryMid,
  Beaker01,
  Beaker02,
  Bell01,
  Bell02,
  Bell03,
  Bell04,
  BellMinus,
  BellOff01,
  BellOff02,
  BellOff03,
  BellPlus,
  BellRinging01,
  BellRinging02,
  BellRinging03,
  BellRinging04,
  BezierCurve01,
  BezierCurve02,
  BezierCurve03,
  BluetoothConnect,
  BluetoothOff,
  BluetoothOn,
  BluetoothSignal,
  Bold01,
  Bold02,
  BoldSquare,
  BookClosed,
  BookOpen01,
  BookOpen02,
  Bookmark,
  BookmarkAdd,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkX,
  Box,
  Brackets,
  BracketsCheck,
  BracketsEllipses,
  BracketsMinus,
  BracketsPlus,
  BracketsSlash,
  BracketsX,
  Breakdown02,
  Briefcase01,
  Briefcase02,
  Browser,
  Brush01,
  Brush02,
  Brush03,
  Building01,
  Building02,
  Building03,
  Building04,
  Building05,
  Building06,
  Building07,
  Building08,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck01,
  CalendarCheck02,
  CalendarDate,
  CalendarHeart01,
  CalendarHeart02,
  CalendarMinus01,
  CalendarMinus02,
  CalendarPlus01,
  CalendarPlus02,
  Camera01,
  Camera02,
  Camera03,
  CameraLens,
  CameraOff,
  CameraPlus,
  Certificate01,
  Certificate02,
  ChartBreakoutCircle,
  ChartBreakoutSquare,
  ChatRobot,
  Check,
  CheckCircle,
  CheckCirclebroken,
  CheckDone01,
  CheckDone02,
  CheckHeart,
  CheckSquare,
  CheckSquareBroken,
  CheckVerified01,
  CheckVerified02,
  CheckVerified03,
  ChevronDown,
  ChevronDownDouble,
  ChevronDownFill,
  ChevronLeft,
  ChevronLeftDouble,
  ChevronRight,
  ChevronRightDouble,
  ChevronRightFill,
  ChevronSelectorHorizontal,
  ChevronSelectorVertical,
  ChevronUp,
  ChevronUpDouble,
  ChevronVerticalExpand,
  ChevronVerticalShrink,
  ChromeCast,
  Circle,
  CircleCut,
  Clapperboard,
  Clipboard,
  ClipboardAttachment,
  ClipboardCheck,
  ClipboardDownload,
  ClipboardMinus,
  ClipboardPlus,
  ClipboardX,
  Clock,
  ClockCheck,
  ClockFastForward,
  ClockPlus,
  ClockRefresh,
  ClockRewind,
  ClockSnooze,
  ClockStopwatch,
  Cloud01,
  Cloud02,
  Cloud03,
  CloudBlank01,
  CloudBlank02,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRaining01,
  CloudRaining02,
  CloudRaining03,
  CloudRaining04,
  CloudRaining05,
  CloudRaining06,
  CloudSnowing01,
  CloudSnowing02,
  CloudSun01,
  CloudSun02,
  CloudSun03,
  Code01,
  Code02,
  CodeBrowser,
  CodeCircle01,
  CodeCircle02,
  CodeCircle03,
  CodeSnippet01,
  CodeSnippet02,
  CodeSquare01,
  CodeSquare02,
  Codepen,
  Coins01,
  Coins02,
  Coins03,
  Coins04,
  CoinsHand,
  CoinsStacked01,
  CoinsStacked02,
  CoinsStacked03,
  CoinsStacked04,
  CoinsSwap01,
  CoinsSwap02,
  Collapse08,
  Colors,
  Colors1,
  Columns01,
  Columns02,
  Columns03,
  Command,
  Compass,
  Compass01,
  Compass02,
  Compass03,
  Connect,
  Container,
  Contrast01,
  Contrast02,
  Contrast03,
  Copy01,
  Copy02,
  Copy03,
  Copy04,
  Copy05,
  Copy06,
  Copy07,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  CpuChip01,
  CpuChip02,
  CreditCard01,
  CreditCard02,
  CreditCardCheck,
  CreditCardDown,
  CreditCardDownload,
  CreditCardEdit,
  CreditCardLock,
  CreditCardMinus,
  CreditCardPlus,
  CreditCardRefresh,
  CreditCardSearch,
  CreditCardShield,
  CreditCardUp,
  CreditCardUpload,
  CreditCardX,
  Crop01,
  Crop02,
  Cryptocurrency01,
  Cryptocurrency02,
  Cryptocurrency03,
  Cryptocurrency04,
  Cube01,
  Cube02,
  Cube03,
  Cube04,
  CubeOutline,
  CurrencyBitcoin,
  CurrencyBitcoinCircle,
  CurrencyDollar,
  CurrencyDollarCircle,
  CurrencyEthereum,
  CurrencyEthereumCircle,
  CurrencyEuro,
  CurrencyEuroCircle,
  CurrencyPound,
  CurrencyPoundCircle,
  CurrencyRuble,
  CurrencyRubleCircle,
  CurrencyRupee,
  CurrencyRupeeCircle,
  CurrencyYen,
  CurrencyYenCircle,
  Cursor01,
  Cursor02,
  Cursor03,
  Cursor04,
  CursorBox,
  CursorClick01,
  CursorClick02,
  Data,
  DataApiSystem,
  DataService,
  DataServiceAdd,
  Database,
  Database01,
  Database02,
  Database03,
  DatabseTable,
  Dataflow01,
  Dataflow02,
  Dataflow03,
  Dataflow04,
  Delete,
  Diamond01,
  Diamond02,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc01,
  Disc02,
  DistributeSpacingHorizontal,
  DistributeSpacingVertical,
  Divide01,
  Divide02,
  Divide03,
  Divider,
  DotPoints01,
  Dotpoints02,
  DotsGrid,
  DotsHorizontal,
  DotsVertical,
  Download01,
  Download02,
  Download03,
  Download04,
  DownloadCloud01,
  DownloadCloud02,
  DragIn,
  Drop,
  Droplets01,
  Droplets02,
  Droplets03,
  Dropper,
  Edit01,
  Edit02,
  Edit03,
  Edit04,
  Edit05,
  Equal,
  EqualNot,
  Eraser,
  Expand01,
  Expand02,
  Expand03,
  Expand04,
  Expand05,
  Expand06,
  Expand08,
  Eye,
  EyeOff,
  FaceContent,
  FaceFrown,
  FaceHappy,
  FaceId,
  FaceIdSquare,
  FaceNeutral,
  FaceSad,
  FaceSmile,
  FaceWink,
  FastBackward,
  FastForward,
  Feather,
  Figma,
  File01,
  File02,
  File03,
  File04,
  File05,
  File06,
  File07,
  FileAttachment01,
  FileAttachment02,
  FileAttachment03,
  FileAttachment04,
  FileAttachment05,
  FileCheck01,
  FileCheck02,
  FileCheck03,
  FileCode01,
  FileCode02,
  FileDownload01,
  FileDownload02,
  FileDownload03,
  FileHeart01,
  FileHeart02,
  FileHeart03,
  FileImport02,
  FileLock01,
  FileLock02,
  FileLock03,
  FileMinus01,
  FileMinus02,
  FileMinus03,
  FilePlus01,
  FilePlus02,
  FilePlus03,
  FileQuestion01,
  FileQuestion02,
  FileQuestion03,
  FileSearch01,
  FileSearch02,
  FileSearch03,
  FileShield01,
  FileShield02,
  FileShield03,
  FileX01,
  FileX02,
  FileX03,
  Film01,
  Film02,
  Film03,
  FilterFunnel01,
  FilterFunnel02,
  FilterLines,
  Fingerprint01,
  Fingerprint02,
  Fingerprint03,
  Fingerprint04,
  Flag01,
  Flag02,
  Flag03,
  Flag04,
  Flag05,
  Flag06,
  Flash,
  FlashOff,
  FlexAlignBottom,
  FlexAlignLeft,
  FlexAlignRight,
  FlexAlignTop,
  FlipBackward,
  FlipForward,
  Folder,
  FolderCheck,
  FolderClosed,
  FolderCode,
  FolderDownload,
  FolderLock,
  FolderMinus,
  FolderPlus,
  FolderQuestion,
  FolderSearch,
  FolderSettings,
  FolderShield,
  FolderX,
  Framer,
  GamingPad01,
  GamingPad02,
  Gift01,
  Gift02,
  GitBranch01,
  GitBranch02,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Glasses01,
  Glasses02,
  Globe01,
  Globe011,
  Globe02,
  Globe021,
  Globe03,
  Globe04,
  Globe05,
  Globe06,
  GoogleChrome,
  GraduationHat01,
  GraduationHat02,
  Grid01,
  Grid02,
  Grid03,
  GridDotsBlank,
  GridDotsBottom,
  GridDotsHorizontalCenter,
  GridDotsLeft,
  GridDotsOuter,
  GridDotsRight,
  GridDotsTop,
  GridDotsVerticalCenter,
  Hand,
  HandsDown,
  HandsDownFill,
  HandsUp,
  HandsUpFill,
  HardDrive,
  Hash01,
  Hash02,
  Heading01,
  Heading02,
  HeadingSquare,
  Headphones01,
  Headphones02,
  Heart,
  HeartCircle,
  HeartHand,
  HeartHexagon,
  HeartOctagon,
  HeartRounded,
  HeartSquare,
  Hearts,
  HelpCircle,
  HelpOctagon,
  HelpSquare,
  Hexagon01,
  Hexagon02,
  Home01,
  Home02,
  Home03,
  Home04,
  Home05,
  HomeLine,
  HomeSmile,
  HorizontalBarChart01,
  HorizontalBarChart02,
  HorizontalBarChart03,
  Hourglass01,
  Hourglass02,
  Hourglass03,
  Hurricane01,
  Hurricane02,
  Hurricane03,
  Image01,
  Image02,
  Image03,
  Image04,
  Image05,
  ImageCheck,
  ImageDown,
  ImageIndentLeft,
  ImageIndentRight,
  ImageLeft,
  ImagePlus,
  ImageRight,
  ImageUp,
  ImageUser,
  ImageUserCheck,
  ImageUserDown,
  ImageUserLeft,
  ImageUserPlus,
  ImageUserRight,
  ImageUserUp,
  ImageUserX,
  ImageX,
  Inbox01,
  Inbox02,
  Infinity,
  Info2,
  InfoCircle,
  InfoHexagon,
  InfoOctagon,
  InfoSquare,
  IntersectCircle,
  IntersectSquare,
  Italic01,
  Italic02,
  ItalicSquare,
  Key01,
  Key02,
  Keyboard01,
  Keyboard02,
  Laptop01,
  Laptop02,
  LayerSingle,
  LayersThree01,
  LayersThree02,
  LayersTwo01,
  LayersTwo02,
  LaygroundGrid02,
  LayoutAlt01,
  LayoutAlt02,
  LayoutAlt03,
  LayoutAlt04,
  LayoutBottom,
  LayoutBottomFill,
  LayoutGrid01,
  LayoutGrid02,
  LayoutLeft,
  LayoutLeftFill,
  LayoutRight,
  LayoutRightFill,
  LayoutTop,
  LayoutTopFill,
  LeftIndent01,
  LeftIndent02,
  LetterSpacing01,
  LetterSpacing02,
  LifeBuoy01,
  LifeBuoy02,
  Lightbulb01,
  Lightbulb02,
  Lightbulb03,
  Lightbulb04,
  Lightbulb05,
  Lightning01,
  Lightning02,
  LineChart,
  LineChartDown01,
  LineChartDown02,
  LineChartDown03,
  LineChartDown04,
  LineChartDown05,
  LineChartUp01,
  LineChartUp02,
  LineChartUp03,
  LineChartUp04,
  LineChartUp05,
  LineHeight,
  Link01,
  Link02,
  Link03,
  Link04,
  Link05,
  LinkBroken01,
  LinkBroken02,
  LinkExternal01,
  LinkExternal02,
  List,
  Loading01,
  Loading02,
  Loading03,
  Lock01,
  Lock02,
  Lock03,
  Lock04,
  LockKeyholeCircle,
  LockKeyholeSquare,
  LockUnlocked01,
  LockUnlocked02,
  LockUnlocked03,
  LockUnlocked04,
  LogIn01,
  LogIn02,
  LogIn03,
  LogIn04,
  LogOut01,
  LogOut02,
  LogOut03,
  LogOut04,
  Luggage01,
  Luggage02,
  Luggage03,
  MagicWand01,
  MagicWand02,
  Mail01,
  Mail02,
  Mail03,
  Mail04,
  Mail05,
  Map01,
  Map02,
  Mark,
  MarkerPin01,
  MarkerPin02,
  MarkerPin03,
  MarkerPin04,
  MarkerPin05,
  MarkerPin06,
  Maximize01,
  Maximize02,
  MediaGithub,
  MediaGithubFill,
  MediaGoogle,
  MediaMicrosoft,
  MedicalCircle,
  MedicalCross,
  MedicalSquare,
  Menu01,
  Menu02,
  Menu03,
  Menu04,
  Menu05,
  MenuLeft,
  MenuRight,
  MessageAlertCircle,
  MessageAlertSquare,
  MessageChatCircle,
  MessageChatSquare,
  MessageCheckCircle,
  MessageCheckSquare,
  MessageCircle01,
  MessageCircle02,
  MessageDotsCircle,
  MessageDotsSquare,
  MessageHeartCircle,
  MessageHeartSquare,
  MessageNotificationCircle,
  MessageNotificationSquare,
  MessagePlusCircle,
  MessagePlusSquare,
  MessageQuestionCircle,
  MessageQuestionSquare,
  MessageSmileCircle,
  MessageSmileSquare,
  MessageSquare01,
  MessageSquare02,
  MessageTextCircle01,
  MessageTextCircle02,
  MessageTextSquare01,
  MessageTextSquare02,
  MessageXCircle,
  MessageXSquare,
  Microphone01,
  Microphone02,
  MicrophoneOff01,
  MicrophoneOff02,
  Microscope,
  Minimize01,
  Minimize02,
  Minus,
  MinusCircle,
  MinusSquare,
  Modem01,
  Modem02,
  Monitor01,
  Monitor02,
  Monitor03,
  Monitor04,
  Monitor05,
  Moon01,
  Moon02,
  MoonEclipse,
  MoonStar,
  Mouse,
  Move,
  MusicNote01,
  MusicNote02,
  MusicNotePlus,
  NavigationPointer01,
  NavigationPointer02,
  NavigationPointerOff01,
  NavigationPointerOff02,
  NotificationBox,
  NotificationMessage,
  NotificationText,
  Numberic,
  Octagon,
  OpenAi,
  OrientationHorizontalFill,
  OrientationVerticalFill,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PackageX,
  Paint,
  PaintPour,
  Palette,
  Paperclip,
  ParagraphSpacing,
  ParagraphWrap,
  Passcode,
  PasscodeLock,
  Passport,
  PauseCircle,
  PauseSquare,
  PenTool01,
  PenTool02,
  PenToolMinus,
  PenToolPlus,
  Pencil01,
  Pencil02,
  PencilLine,
  Pentagon,
  Percent01,
  Percent02,
  Percent03,
  Perspective01,
  Perspective02,
  Phone,
  Phone01,
  Phone02,
  PhoneCall01,
  PhoneCall02,
  PhoneHangUp,
  PhoneIncoming01,
  PhoneIncoming02,
  PhoneOutgoing01,
  PhoneOutgoing02,
  PhonePause,
  PhonePlus,
  PhoneX,
  PieChart01,
  PieChart02,
  PieChart03,
  PieChart04,
  PiggyBank01,
  PiggyBank02,
  Pilcrow01,
  Pilcrow02,
  PilcrowSquare,
  Pin01,
  Pin02,
  Placeholder,
  Plane,
  Play,
  PlayCircle,
  PlaySquare,
  Plus,
  PlusCircle,
  PlusSquare,
  Podcast,
  Power01,
  Power02,
  Power03,
  PresentationChart01,
  PresentationChart02,
  PresentationChart03,
  Printer,
  PuzzlePiece01,
  PuzzlePiece02,
  QrCode01,
  QrCode02,
  Question,
  Receipt,
  ReceiptCheck,
  Recording01,
  Recording02,
  Recording03,
  Redeploy,
  Reflect01,
  Reflect02,
  RefreshCcw01,
  RefreshCcw02,
  RefreshCcw03,
  RefreshCcw04,
  RefreshCcw05,
  RefreshCw01,
  RefreshCw02,
  RefreshCw03,
  RefreshCw04,
  RefreshCw05,
  Repeat01,
  Repeat02,
  Repeat03,
  Repeat04,
  ReverseLeft,
  ReverseRight,
  Right,
  RightIndent01,
  RightIndent02,
  Rocket01,
  Rocket02,
  RollerBrush,
  Route,
  Rows01,
  Rows02,
  Rows03,
  Rss01,
  Rss02,
  Ruler,
  Run,
  RunFill,
  Safe,
  Sale01,
  Sale02,
  Sale03,
  Sale04,
  Save01,
  Save02,
  Save03,
  Scale01,
  Scale02,
  Scale03,
  Scales01,
  Scales02,
  Scan,
  Scissors01,
  Scissors02,
  ScissorsCut01,
  ScissorsCut02,
  SearchLg,
  SearchMd,
  SearchRefraction,
  SearchSm,
  SeeMore,
  SeeShort,
  Send01,
  Send02,
  Send03,
  Series,
  Server01,
  Server02,
  Server03,
  Server04,
  Server05,
  Server06,
  Service,
  Settings01,
  Settings02,
  Settings03,
  Settings04,
  Share01,
  Share02,
  Share03,
  Share04,
  Share05,
  Share06,
  Share07,
  Shield01,
  Shield02,
  Shield03,
  ShieldDollar,
  ShieldOff,
  ShieldPlus,
  ShieldTick,
  ShieldUser,
  ShieldZap,
  ShoppingBag01,
  ShoppingBag02,
  ShoppingBag03,
  ShoppingCart01,
  ShoppingCart02,
  ShoppingCart03,
  Shuffle01,
  Shuffle02,
  Signal01,
  Signal02,
  Signal03,
  Simcard,
  Skew,
  SkipBack,
  SkipForward,
  SlashCircle01,
  SlashCircle02,
  SlashDivider,
  SlashOctagon,
  Sliders01,
  Sliders02,
  Sliders03,
  Sliders04,
  Snowflake01,
  Snowflake02,
  SpacingHeight01,
  SpacingHeight02,
  SpacingWidth01,
  SpacingWidth02,
  Speaker01,
  Speaker02,
  Speaker03,
  Speedometer01,
  Speedometer02,
  Speedometer03,
  Speedometer04,
  Square,
  Stand,
  Star01,
  Star02,
  Star03,
  Star04,
  Star05,
  Star06,
  Star07,
  Stars01,
  Stars02,
  Stars03,
  StickerCircle,
  StickerSquare,
  Stop,
  StopCircle,
  StopSquare,
  Strikethrough01,
  Strikethrough02,
  StrikethroughSquare,
  String01,
  Subscript,
  Sun,
  SunSetting01,
  SunSetting02,
  SunSetting03,
  Sunrise,
  Sunset,
  SwitchHorizontal01,
  SwitchHorizontal02,
  SwitchVertical01,
  SwitchVertical02,
  SystemDatabase,
  SystemMode,
  Table,
  Tablet01,
  Tablet02,
  Tag01,
  Tag02,
  Tag03,
  Target01,
  Target02,
  Target03,
  Target04,
  Target05,
  Telescope,
  Terminal,
  TerminalBrowser,
  TerminalCircle,
  TerminalSquare,
  TextInput,
  Thermometer01,
  Thermometer02,
  Thermometer03,
  ThermometerCold,
  ThermometerWarm,
  ThumbsDown,
  ThumbsUp,
  Ticket01,
  Ticket02,
  Toggle01Left,
  Toggle01Right,
  Toggle02Left,
  Toggle02Right,
  Toggle03Left,
  Toggle03Right,
  Tool01,
  Tool02,
  Tools,
  Train,
  Tram,
  Transform,
  Translate01,
  Translate02,
  Trash01,
  Trash02,
  Trash03,
  Trash04,
  TrendDown01,
  TrendDown02,
  TrendUp01,
  TrendUp02,
  Triangle,
  Trophy01,
  Trophy02,
  Truck01,
  Truck02,
  Tv01,
  Tv02,
  Tv03,
  Type01,
  Type02,
  TypeSquare,
  TypeStrikethrough01,
  TypeStrikethrough02,
  Types02,
  Umbrella01,
  Umbrella02,
  Umbrella03,
  Underline01,
  Underline02,
  UnderlineSquare,
  Upload01,
  Upload02,
  Upload03,
  Upload04,
  UploadCloud01,
  UploadCloud02,
  UsbFlashDrive,
  User01,
  User02,
  User03,
  UserCheck01,
  UserCheck02,
  UserCircle,
  UserDown01,
  UserDown02,
  UserEdit,
  UserLeft01,
  UserLeft02,
  UserMinus01,
  UserMinus02,
  UserPlus01,
  UserPlus02,
  UserRight01,
  UserRight02,
  UserSquare,
  UserUp01,
  UserUp02,
  UserX01,
  UserX02,
  Users01,
  Users02,
  Users03,
  UsersCheck,
  UsersDown,
  UsersEdit,
  UsersLeft,
  UsersMinus,
  UsersPlus,
  UsersRight,
  UsersUp,
  UsersX,
  Variable,
  VideoRecorder,
  VideoRecorderOff,
  Virus,
  Voicemail,
  VolumeMax,
  VolumeMin,
  VolumeMinus,
  VolumePlus,
  VolumeX,
  Wallet01,
  Wallet02,
  Wallet03,
  Wallet04,
  Wallet05,
  WatchCircle,
  WatchSquare,
  Waves,
  Webcam01,
  Webcam02,
  Wifi,
  WifiOff,
  Wind01,
  Wind02,
  Wind03,
  X,
  XAxis,
  XCircle,
  XClose,
  XSquare,
  YAxis,
  Youtube,
  Zap,
  ZapCircle,
  ZapFast,
  ZapOff,
  ZapSquare,
  ZoomIn,
  ZoomOut
}
