export default {
  AppShell: 'AppShell',
  CodeBlock: 'CodeBlock',
  CollapsibleCard: 'CollapsibleCard',
  CopyText: 'CopyText',
  DateTimePicker: 'DateTimePicker',
  Dot: 'Dot',
  DotBadge: 'DotBadge',
  Form: 'Form',
  LabelTooltip: 'LabelTooltip',
  PageShell: 'PageShell',
  PhoneInput: 'PhoneInput',
  ProMultiSelect: 'ProMultiSelect',
  PropertyCard: 'PropertyCard',
  SearchArea: 'SearchArea',
  TableBasic: 'TableBasic',
  TablePro: 'TablePro',
  TransferTree: 'TransferTree',
  Tree: 'Tree',
  Typography: 'Typography',
  TimeRangePicker: 'TimeRangePicker'
}
