/**
 * DO NOT EDIT THIS FILE, THE CONTENT IS AUTO-GENERATED
 * RUN `yarn gen:icon` TO RE-GENERATE
 */
import { ReactComponent as AiExplore01 } from './AiExplore01.svg'
import { ReactComponent as AlertCircle } from './AlertCircle.svg'
import { ReactComponent as AlertTriangle } from './AlertTriangle.svg'
import { ReactComponent as AlertTriangleFill } from './AlertTriangleFill.svg'
import { ReactComponent as AlignLeft01 } from './AlignLeft01.svg'
import { ReactComponent as AlignRight01 } from './AlignRight01.svg'
import { ReactComponent as ArrowDown } from './ArrowDown.svg'
import { ReactComponent as ArrowLeft } from './ArrowLeft.svg'
import { ReactComponent as ArrowRight } from './ArrowRight.svg'
import { ReactComponent as ArrowUp } from './ArrowUp.svg'
import { ReactComponent as Atom01 } from './Atom01.svg'
import { ReactComponent as BarChart04 } from './BarChart04.svg'
import { ReactComponent as BarChart07 } from './BarChart07.svg'
import { ReactComponent as BarChart08 } from './BarChart08.svg'
import { ReactComponent as BarHorizontal } from './BarHorizontal.svg'
import { ReactComponent as BarVertical } from './BarVertical.svg'
import { ReactComponent as BookClosed } from './BookClosed.svg'
import { ReactComponent as BookOpen02 } from './BookOpen02.svg'
import { ReactComponent as Brackets } from './Brackets.svg'
import { ReactComponent as BracketsEllipses } from './BracketsEllipses.svg'
import { ReactComponent as Breakdown02 } from './Breakdown02.svg'
import { ReactComponent as Building05 } from './Building05.svg'
import { ReactComponent as Calendar } from './Calendar.svg'
import { ReactComponent as ChatRobot } from './ChatRobot.svg'
import { ReactComponent as Check } from './Check.svg'
import { ReactComponent as CheckCircle } from './CheckCircle.svg'
import { ReactComponent as CheckCirclebroken } from './CheckCirclebroken.svg'
import { ReactComponent as CheckSquareBroken } from './CheckSquareBroken.svg'
import { ReactComponent as CheckVerified02 } from './CheckVerified02.svg'
import { ReactComponent as ChevronDown } from './ChevronDown.svg'
import { ReactComponent as ChevronDownFill } from './ChevronDownFill.svg'
import { ReactComponent as ChevronLeft } from './ChevronLeft.svg'
import { ReactComponent as ChevronRight } from './ChevronRight.svg'
import { ReactComponent as ChevronRightFill } from './ChevronRightFill.svg'
import { ReactComponent as ChevronUp } from './ChevronUp.svg'
import { ReactComponent as ChevronVerticalExpand } from './ChevronVerticalExpand.svg'
import { ReactComponent as ChevronVerticalShrink } from './ChevronVerticalShrink.svg'
import { ReactComponent as Clock } from './Clock.svg'
import { ReactComponent as CodeBrowser } from './CodeBrowser.svg'
import { ReactComponent as CodeCircle02 } from './CodeCircle02.svg'
import { ReactComponent as CodeCircle03 } from './CodeCircle03.svg'
import { ReactComponent as Collapse08 } from './Collapse08.svg'
import { ReactComponent as Connect } from './Connect.svg'
import { ReactComponent as Copy01 } from './Copy01.svg'
import { ReactComponent as Copy03 } from './Copy03.svg'
import { ReactComponent as Copy07 } from './Copy07.svg'
import { ReactComponent as CurrencyDollarCircle } from './CurrencyDollarCircle.svg'
import { ReactComponent as CursorClick01 } from './CursorClick01.svg'
import { ReactComponent as DataApiSystem } from './DataApiSystem.svg'
import { ReactComponent as Database } from './Database.svg'
import { ReactComponent as Database01 } from './Database01.svg'
import { ReactComponent as Database03 } from './Database03.svg'
import { ReactComponent as DatabseTable } from './DatabseTable.svg'
import { ReactComponent as Dataflow03 } from './Dataflow03.svg'
import { ReactComponent as DataService } from './DataService.svg'
import { ReactComponent as DataServiceAdd } from './DataServiceAdd.svg'
import { ReactComponent as DotPoints01 } from './DotPoints01.svg'
import { ReactComponent as DotsHorizontal } from './DotsHorizontal.svg'
import { ReactComponent as DotsVertical } from './DotsVertical.svg'
import { ReactComponent as Download01 } from './Download01.svg'
import { ReactComponent as DownloadCloud01 } from './DownloadCloud01.svg'
import { ReactComponent as DragIn } from './DragIn.svg'
import { ReactComponent as Edit03 } from './Edit03.svg'
import { ReactComponent as Edit05 } from './Edit05.svg'
import { ReactComponent as Eraser } from './Eraser.svg'
import { ReactComponent as Expand01 } from './Expand01.svg'
import { ReactComponent as Expand08 } from './Expand08.svg'
import { ReactComponent as Eye } from './Eye.svg'
import { ReactComponent as EyeOff } from './EyeOff.svg'
import { ReactComponent as FaceNeutral } from './FaceNeutral.svg'
import { ReactComponent as FaceSmile } from './FaceSmile.svg'
import { ReactComponent as File02 } from './File02.svg'
import { ReactComponent as File05 } from './File05.svg'
import { ReactComponent as File06 } from './File06.svg'
import { ReactComponent as FileImport02 } from './FileImport02.svg'
import { ReactComponent as FilterFunnel01 } from './FilterFunnel01.svg'
import { ReactComponent as FilterLines } from './FilterLines.svg'
import { ReactComponent as FolderSettings } from './FolderSettings.svg'
import { ReactComponent as Github } from './Github.svg'
import { ReactComponent as Glasses01 } from './Glasses01.svg'
import { ReactComponent as Grid01 } from './Grid01.svg'
import { ReactComponent as HandsDown } from './HandsDown.svg'
import { ReactComponent as HandsDownFill } from './HandsDownFill.svg'
import { ReactComponent as HandsUp } from './HandsUp.svg'
import { ReactComponent as HandsUpFill } from './HandsUpFill.svg'
import { ReactComponent as HeartHand } from './HeartHand.svg'
import { ReactComponent as HelpCircle } from './HelpCircle.svg'
import { ReactComponent as HomeLine } from './HomeLine.svg'
import { ReactComponent as Inbox01 } from './Inbox01.svg'
import { ReactComponent as Info2 } from './Info2.svg'
import { ReactComponent as InfoCircle } from './InfoCircle.svg'
import { ReactComponent as Key02 } from './Key02.svg'
import { ReactComponent as LaygroundGrid02 } from './LaygroundGrid02.svg'
import { ReactComponent as LayoutAlt03 } from './LayoutAlt03.svg'
import { ReactComponent as LayoutBottom } from './LayoutBottom.svg'
import { ReactComponent as LayoutBottomFill } from './LayoutBottomFill.svg'
import { ReactComponent as LayoutLeft } from './LayoutLeft.svg'
import { ReactComponent as LayoutLeftFill } from './LayoutLeftFill.svg'
import { ReactComponent as LayoutRight } from './LayoutRight.svg'
import { ReactComponent as LayoutRightFill } from './LayoutRightFill.svg'
import { ReactComponent as LayoutTop } from './LayoutTop.svg'
import { ReactComponent as LayoutTopFill } from './LayoutTopFill.svg'
import { ReactComponent as LeftIndent01 } from './LeftIndent01.svg'
import { ReactComponent as LifeBuoy01 } from './LifeBuoy01.svg'
import { ReactComponent as LineChart } from './LineChart.svg'
import { ReactComponent as LineChartUp01 } from './LineChartUp01.svg'
import { ReactComponent as Link03 } from './Link03.svg'
import { ReactComponent as LinkExternal01 } from './LinkExternal01.svg'
import { ReactComponent as List } from './List.svg'
import { ReactComponent as Lock01 } from './Lock01.svg'
import { ReactComponent as LockUnlocked01 } from './LockUnlocked01.svg'
import { ReactComponent as LogOut03 } from './LogOut03.svg'
import { ReactComponent as MagicWand02 } from './MagicWand02.svg'
import { ReactComponent as MediaGithub } from './MediaGithub.svg'
import { ReactComponent as MediaGithubFill } from './MediaGithubFill.svg'
import { ReactComponent as MediaGoogle } from './MediaGoogle.svg'
import { ReactComponent as MediaMicrosoft } from './MediaMicrosoft.svg'
import { ReactComponent as Menu01 } from './Menu01.svg'
import { ReactComponent as MenuLeft } from './MenuLeft.svg'
import { ReactComponent as MenuRight } from './MenuRight.svg'
import { ReactComponent as MessageChatSquare } from './MessageChatSquare.svg'
import { ReactComponent as MessageSquare02 } from './MessageSquare02.svg'
import { ReactComponent as MessageTextSquare01 } from './MessageTextSquare01.svg'
import { ReactComponent as MessageTextSquare02 } from './MessageTextSquare02.svg'
import { ReactComponent as Minimize01 } from './Minimize01.svg'
import { ReactComponent as Minus } from './Minus.svg'
import { ReactComponent as MinusCircle } from './MinusCircle.svg'
import { ReactComponent as Moon01 } from './Moon01.svg'
import { ReactComponent as NotificationBox } from './NotificationBox.svg'
import { ReactComponent as Numberic } from './Numberic.svg'
import { ReactComponent as OpenAi } from './OpenAi.svg'
import { ReactComponent as OrientationHorizontalFill } from './OrientationHorizontalFill.svg'
import { ReactComponent as OrientationVerticalFill } from './OrientationVerticalFill.svg'
import { ReactComponent as PackagePlus } from './PackagePlus.svg'
import { ReactComponent as ParagraphSpacing } from './ParagraphSpacing.svg'
import { ReactComponent as PauseCircle } from './PauseCircle.svg'
import { ReactComponent as Pencil01 } from './Pencil01.svg'
import { ReactComponent as PieChart03 } from './PieChart03.svg'
import { ReactComponent as PlayCircle } from './PlayCircle.svg'
import { ReactComponent as Plus } from './Plus.svg'
import { ReactComponent as PlusSquare } from './PlusSquare.svg'
import { ReactComponent as Question } from './Question.svg'
import { ReactComponent as Redeploy } from './Redeploy.svg'
import { ReactComponent as RefreshCw01 } from './RefreshCw01.svg'
import { ReactComponent as RefreshCw02 } from './RefreshCw02.svg'
import { ReactComponent as RefreshCw04 } from './RefreshCw04.svg'
import { ReactComponent as Repeat04 } from './Repeat04.svg'
import { ReactComponent as Right } from './Right.svg'
import { ReactComponent as RightIndent01 } from './RightIndent01.svg'
import { ReactComponent as Rocket02 } from './Rocket02.svg'
import { ReactComponent as Run } from './Run.svg'
import { ReactComponent as RunFill } from './RunFill.svg'
import { ReactComponent as Scale02 } from './Scale02.svg'
import { ReactComponent as Scale03 } from './Scale03.svg'
import { ReactComponent as SearchLg } from './SearchLg.svg'
import { ReactComponent as SeeMore } from './SeeMore.svg'
import { ReactComponent as SeeShort } from './SeeShort.svg'
import { ReactComponent as Send03 } from './Send03.svg'
import { ReactComponent as Series } from './Series.svg'
import { ReactComponent as Server02 } from './Server02.svg'
import { ReactComponent as Server05 } from './Server05.svg'
import { ReactComponent as Service } from './Service.svg'
import { ReactComponent as Settings01 } from './Settings01.svg'
import { ReactComponent as Settings02 } from './Settings02.svg'
import { ReactComponent as Shield03 } from './Shield03.svg'
import { ReactComponent as ShieldTick } from './ShieldTick.svg'
import { ReactComponent as ShieldUser } from './ShieldUser.svg'
import { ReactComponent as Star04 } from './Star04.svg'
import { ReactComponent as String01 } from './String01.svg'
import { ReactComponent as Sun } from './Sun.svg'
import { ReactComponent as SwitchHorizontal02 } from './SwitchHorizontal02.svg'
import { ReactComponent as SwitchVertical02 } from './SwitchVertical02.svg'
import { ReactComponent as SystemDatabase } from './SystemDatabase.svg'
import { ReactComponent as SystemMode } from './SystemMode.svg'
import { ReactComponent as Table } from './Table.svg'
import { ReactComponent as Tools } from './Tools.svg'
import { ReactComponent as Trash01 } from './Trash01.svg'
import { ReactComponent as Types02 } from './Types02.svg'
import { ReactComponent as UploadCloud01 } from './UploadCloud01.svg'
import { ReactComponent as UserCircle } from './UserCircle.svg'
import { ReactComponent as Users01 } from './Users01.svg'
import { ReactComponent as UsersPlus } from './UsersPlus.svg'
import { ReactComponent as Variable } from './Variable.svg'
import { ReactComponent as Wifi } from './Wifi.svg'
import { ReactComponent as XAxis } from './XAxis.svg'
import { ReactComponent as XCircle } from './XCircle.svg'
import { ReactComponent as XClose } from './XClose.svg'
import { ReactComponent as YAxis } from './YAxis.svg'

export const ICON_MAP = {
  AiExplore01,
  AlertCircle,
  AlertTriangle,
  AlertTriangleFill,
  AlignLeft01,
  AlignRight01,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom01,
  BarChart04,
  BarChart07,
  BarChart08,
  BarHorizontal,
  BarVertical,
  BookClosed,
  BookOpen02,
  Brackets,
  BracketsEllipses,
  Breakdown02,
  Building05,
  Calendar,
  ChatRobot,
  Check,
  CheckCircle,
  CheckCirclebroken,
  CheckSquareBroken,
  CheckVerified02,
  ChevronDown,
  ChevronDownFill,
  ChevronLeft,
  ChevronRight,
  ChevronRightFill,
  ChevronUp,
  ChevronVerticalExpand,
  ChevronVerticalShrink,
  Clock,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Collapse08,
  Connect,
  Copy01,
  Copy03,
  Copy07,
  CurrencyDollarCircle,
  CursorClick01,
  DataApiSystem,
  DataService,
  DataServiceAdd,
  Database,
  Database01,
  Database03,
  DatabseTable,
  Dataflow03,
  DotPoints01,
  DotsHorizontal,
  DotsVertical,
  Download01,
  DownloadCloud01,
  DragIn,
  Edit03,
  Edit05,
  Eraser,
  Expand01,
  Expand08,
  Eye,
  EyeOff,
  FaceNeutral,
  FaceSmile,
  File02,
  File05,
  File06,
  FileImport02,
  FilterFunnel01,
  FilterLines,
  FolderSettings,
  Github,
  Glasses01,
  Grid01,
  HandsDown,
  HandsDownFill,
  HandsUp,
  HandsUpFill,
  HeartHand,
  HelpCircle,
  HomeLine,
  Inbox01,
  Info2,
  InfoCircle,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LayoutBottom,
  LayoutBottomFill,
  LayoutLeft,
  LayoutLeftFill,
  LayoutRight,
  LayoutRightFill,
  LayoutTop,
  LayoutTopFill,
  LeftIndent01,
  LifeBuoy01,
  LineChart,
  LineChartUp01,
  Link03,
  LinkExternal01,
  List,
  Lock01,
  LockUnlocked01,
  LogOut03,
  MagicWand02,
  MediaGithub,
  MediaGithubFill,
  MediaGoogle,
  MediaMicrosoft,
  Menu01,
  MenuLeft,
  MenuRight,
  MessageChatSquare,
  MessageSquare02,
  MessageTextSquare01,
  MessageTextSquare02,
  Minimize01,
  Minus,
  MinusCircle,
  Moon01,
  NotificationBox,
  Numberic,
  OpenAi,
  OrientationHorizontalFill,
  OrientationVerticalFill,
  PackagePlus,
  ParagraphSpacing,
  PauseCircle,
  Pencil01,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  Question,
  Redeploy,
  RefreshCw01,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Rocket02,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  SeeMore,
  SeeShort,
  Send03,
  Series,
  Server02,
  Server05,
  Service,
  Settings01,
  Settings02,
  SystemMode,
  Shield03,
  ShieldTick,
  ShieldUser,
  Star04,
  String01,
  Sun,
  SwitchHorizontal02,
  SwitchVertical02,
  SystemDatabase,
  Table,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  UsersPlus,
  Variable,
  Wifi,
  XAxis,
  XCircle,
  XClose,
  YAxis
}

export {
  AiExplore01,
  AlertCircle,
  AlertTriangle,
  AlertTriangleFill,
  AlignLeft01,
  AlignRight01,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom01,
  BarChart04,
  BarChart07,
  BarChart08,
  BarHorizontal,
  BarVertical,
  BookClosed,
  BookOpen02,
  Brackets,
  BracketsEllipses,
  Breakdown02,
  Building05,
  Calendar,
  ChatRobot,
  Check,
  CheckCircle,
  CheckCirclebroken,
  CheckSquareBroken,
  CheckVerified02,
  ChevronDown,
  ChevronDownFill,
  ChevronLeft,
  ChevronRight,
  ChevronRightFill,
  ChevronUp,
  ChevronVerticalExpand,
  ChevronVerticalShrink,
  Clock,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Collapse08,
  Connect,
  Copy01,
  Copy03,
  Copy07,
  CurrencyDollarCircle,
  CursorClick01,
  DataApiSystem,
  DataService,
  DataServiceAdd,
  Database,
  Database01,
  Database03,
  DatabseTable,
  Dataflow03,
  DotPoints01,
  DotsHorizontal,
  DotsVertical,
  Download01,
  DownloadCloud01,
  DragIn,
  Edit03,
  Edit05,
  Eraser,
  Expand01,
  Expand08,
  Eye,
  EyeOff,
  FaceNeutral,
  FaceSmile,
  File02,
  File05,
  File06,
  FileImport02,
  FilterFunnel01,
  FilterLines,
  FolderSettings,
  Github,
  Glasses01,
  Grid01,
  HandsDown,
  HandsDownFill,
  HandsUp,
  HandsUpFill,
  HeartHand,
  HelpCircle,
  HomeLine,
  Inbox01,
  Info2,
  InfoCircle,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LayoutBottom,
  LayoutBottomFill,
  LayoutLeft,
  LayoutLeftFill,
  LayoutRight,
  LayoutRightFill,
  LayoutTop,
  LayoutTopFill,
  LeftIndent01,
  LifeBuoy01,
  LineChart,
  LineChartUp01,
  Link03,
  LinkExternal01,
  List,
  Lock01,
  LockUnlocked01,
  LogOut03,
  MagicWand02,
  MediaGithub,
  MediaGithubFill,
  MediaGoogle,
  MediaMicrosoft,
  Menu01,
  MenuLeft,
  MenuRight,
  MessageChatSquare,
  MessageSquare02,
  MessageTextSquare01,
  MessageTextSquare02,
  Minimize01,
  Minus,
  MinusCircle,
  Moon01,
  NotificationBox,
  Numberic,
  OpenAi,
  OrientationHorizontalFill,
  OrientationVerticalFill,
  PackagePlus,
  ParagraphSpacing,
  PauseCircle,
  Pencil01,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  Question,
  Redeploy,
  RefreshCw01,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Rocket02,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  SeeMore,
  SeeShort,
  Send03,
  Series,
  Server02,
  Server05,
  Service,
  Settings01,
  Settings02,
  SystemMode,
  Shield03,
  ShieldTick,
  ShieldUser,
  Star04,
  String01,
  Sun,
  SwitchHorizontal02,
  SwitchVertical02,
  SystemDatabase,
  Table,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  UsersPlus,
  Variable,
  Wifi,
  XAxis,
  XCircle,
  XClose,
  YAxis
}
