export const components = {
  core: {
    Layout: ['AppShell', 'AspectRatio', 'Center', 'Container', 'Flex', 'Grid', 'Group', 'SimpleGrid', 'Space', 'Stack'],
    Inputs: [
      'Checkbox',
      'Chip',
      'ColorInput',
      'ColorPicker',
      'HueSlider',
      'AlphaSlider',
      'Fieldset',
      'FileInput',
      'Input',
      'JsonInput',
      'NativeSelect',
      'NumberInput',
      'PasswordInput',
      'PinInput',
      'Radio',
      'Rating',
      'SegmentedControl',
      'Slider',
      'Switch',
      'Textarea',
      'TextInput'
    ],
    Combobox: ['Autocomplete', 'Combobox', 'MultiSelect', 'Pill', 'PillsInput', 'Select', 'TagsInput'],
    Buttons: ['ActionIcon', 'Button', 'CloseButton', 'CopyButton', 'FileButton', 'UnstyledButton'],
    Navigation: ['Anchor', 'Breadcrumbs', 'Burger', 'NavLink', 'Pagination', 'Stepper', 'Tabs', 'Tree'],
    Feedback: ['Alert', 'Loader', 'Notification', 'Progress', 'RingProgress', 'SemiCircleProgress', 'Skeleton'],
    Overlays: [
      'Affix',
      'Dialog',
      'Drawer',
      'FloatingIndicator',
      'HoverCard',
      'LoadingOverlay',
      'Menu',
      'Modal',
      'Overlay',
      'Popover',
      'Tooltip'
    ],
    'Data display': [
      'Accordion',
      'Avatar',
      'BackgroundImage',
      'Badge',
      'Card',
      'ColorSwatch',
      'Image',
      'Indicator',
      'Kbd',
      'NumberFormatter',
      'Spoiler',
      'ThemeIcon',
      'Timeline'
    ],
    Typography: [
      'Blockquote',
      'Code',
      'Highlight',
      'List',
      'Mark',
      'Table',
      'Text',
      'Title',
      'TypographyStylesProvider'
    ],
    Misc: ['Box', 'Collapse', 'Divider', 'FocusTrap', 'Paper', 'Portal', 'ScrollArea', 'Transition', 'VisuallyHidden'],
    Dates: [
      'DatesProvider',
      'Calendar',
      'DateInput',
      'DateTimePicker',
      'DatePicker',
      'DatePickerInput',
      'MonthPicker',
      'MonthPickerInput',
      'YearPicker',
      'YearPickerInput',
      'TimeInput'
    ]
  }
}
