# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Github Packages

on:
  push:
    branches:
      - master
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @tidbcloud:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: pnpm -r install

      - name: Build Package
        run: pnpm -r build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          commit: "release: bump versions"
          title: "release: bump versions"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
